### ISSUE TITLE
Feature Request: Support #include() in resolver mapping templates

### ISSUE THREAD

**Issue by vicary** [aws/aws-appsync-community#101]
Currently when resolver logic gets long we are forced to go Lambda route, but usually the only output is one of the supported data source in AppSync.

Adding one more hop in the infrastructure not only induced unnecessary costs, there is also a notable overhead especially for N+1 problem where Lambda struggles with.

We tried to migrate some of our application logic to pure Velocity, but lacking a file system, or some kind of bundler, it is a pain for our team to really scale the app.

Is it possible to support the `#include()` directive so we can write more structured code?

**Comment by itrestian** [comment]
Thank you for the feedback. This is a feature request at this point which is included in our backlog. However I cannot comment on a timeline for the availability of the feature.

**Comment by vicary** [comment]
It is good to hear it at least in the backlog!

Would you mind sharing about the direction it is heading?

Will it be a resource loader for S3 or something totally different?

**Comment by itrestian** [comment]
I'm not entirely sure about your use case but if you're interested in integrating external files in your app, we currently have support for complex objects as described here:

https://dev.to/dabit3/graphql-tutorial-how-to-manage-image-file-uploads-downloads-with-aws-appsync-aws-amplify-hga

**Comment by vicary** [comment]
Oh no, it's not about user generated data, but the resolver mapping themselves.

We are writing huge chunks of Velocity codes in resolvers as a mean to skip one hop into Lambda and directly to other data sources.

I am interested in the way you planned to implement the `#include()` statement behind the scene in AppSync, like, where will the target files being imported from?

**Comment by vicary** [comment]
The `APPSYNC_JS` runtime chained with a bundler is more straight forward and preferred by my team, I am closing this issue in favor of that.
