### ISSUE TITLE
Appsync creating bucket in wrong region

### ISSUE THREAD

**Issue by myfairshare** [aws/aws-appsync-community#102]
I have created an amplify app and mocked it locally following Nader Dabits workshop on youtube, all good, created a gql schema and amplify gives me a graphiql testing endpoint and I wired it up to a react app.  So I then added auth via the latest amplify cli 4.18.0, then I did **amplify push** as instructed in the docs.  But I get errors saying appsync is trying to create the schema in a bucket in us-east-1, but I am in eu-west-1 and configured my amplify app as eu-west-1.  So **amplify push** is not working because of this error.  Could someone please shed some light on this, thank you very much.

> _Following resources failed
> 
> Resource Name: GraphQLSchema (AWS::AppSync::GraphQLSchema)
> Event Type: create
> Reason: The bucket is in this region: us-east-1. Please use this region to retry the request (Service: Amazon S3; Status
>  Code: 301; Error Code: PermanentRedirect;_

**Comment by itrestian** [comment]
I would reach out on the amplify-cli github for this issue https://github.com/aws-amplify/amplify-cli/

**Comment by JanBussieck** [comment]
Seems related to https://github.com/aws-amplify/amplify-cli/issues/4129

**Comment by myfairshare** [comment]
Thank you both, it was y own fault having old aws env variables from a different account on my machine.
