### ISSUE TITLE
Single quote in VTL comment breaks template

### ISSUE THREAD

**Issue by SteffeyDev** [aws/aws-appsync-community#105]
Not sure if this is the correct way to report, but when deploying a custom VTL template through AWS Amplify, I discovered that a single quote character in a single-line comment causes a validation error.  For example, the following line would cause the template to error out (unexpected character 't'):
```
## Can't do this or that
```
The apostrophe in "Can't" causes the issue, even though this is a comment line and should be ignored

**Comment by jpignata** [comment]
I'm not seeing this currently, please tell me if you're still seeing this.
