### ISSUE TITLE
AWSURL doesn't support Top Level Domain .store

### ISSUE THREAD

**Issue by bpw-123** [aws/aws-appsync-community#107]
Hi, 
this is the first time I post something in such a forum and I hope I address it right.

## Problem
We use AWS AppSync and Amplify. For saving domains in our DB, we use the [AppSync Defined Scalars](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html) data type called `AWSURL`.

For the moment I am facing problems with the domain that ends on `.store`. I read the documentation but it doesn't say, which domains are supported.

## Example Schema

The schema.graphql looks like this:
```
type User @model {
   id: ID!
   url: AWSURL
   name: [Name]
}
```

## Tests
I tested other domain endings and they worked so far.

**Comment by itrestian** [comment]
We have made a fix for this that is currently available in the us-west-2 and the us-east-1 regions and will eventually be available in all regions. Can you test and see if it fits your needs?

**Comment by itrestian** [comment]
This should be available everywhere at this point.
