### ISSUE TITLE
Subscriptions with arguments not working with chat sample

### ISSUE THREAD

**Issue by Stereobit** [aws/aws-appsync-community#109]
**Describe the bug**
I'm not able to receive any updates from subscriptions when using arguments in my application. I am able to reproduce the issue using the chat sample app while only using the AWS console so I'll leave any other setup out here.

**To Reproduce**
* Create new AppSync App
* Pick Chat Sample
* Run Query

```
subscription {
  subscribeToNewMessage(conversationId: "myNewId") {
    content
    createdAt
  }
}
```

* Run Query

```
mutation CreateMessage {
  createMessage(content: "Second!" conversationId: "myNewId" createdAt: "This afternoon" id: "messageOneId") {
    content
    createdAt
  }
}
```

**Expected behavior**
The subscription receives the results of the `createMessage` mutation.

**Additional context**
If I remove the argument from the subscription it works as expected 
```
type Subscription {
  subscribeToNewMessage: Message @aws_subscribe(mutations: ["createMessage"])
}

subscription {
  subscribeToNewMessage {
    content
    createdAt
  }
}
```

**Comment by Sunac** [comment]
Maybe I'm wrong, but at first sight it looks you should include your argument 'conversationId' in list of subscription fields. 
Responses are filtered out by the argument if you specify them, and in your response you didn't add that conversationId.

**Comment by Stereobit** [comment]
> Maybe I'm wrong, but at first sight it looks you should include your argument 'conversationId' in list of mutation fields.
> Responses are filtered out by the argument if you specify them, and your response from mutation must contain that conversationId if you want to be received by subscription.
> Subscription response will just reflect what's sent from the mutation.

Hmmm, that fixed it. This seems very confusing to me my assumption was that it is filtered by the argument I send in the mutation, not the one that I query for. Thanks for clearing this up.

**Comment by Sunac** [comment]
You're welcome ;)
You can check this blog post for better understanding.

**Comment by Sunac** [comment]
Wlcm ;). 
For better understanding, you can check this blog post:https://aws.amazon.com/blogs/mobile/appsync-realtime/
