### ISSUE TITLE
Error: Unsupported element '$[condition][returnValuesOnConditionCheckFailure]'.

### ISSUE THREAD

**Issue by zolcsi** [aws/aws-appsync-community#110]
Hi, 
I am having the following request mapping template, resulting this error:
`Error: Unsupported element '$[condition][returnValuesOnConditionCheckFailure]'.`

Can somebody help me how to use it correctly?
I would like to omit the violated record to be delivered back to the client.
Here is my ..req.vtl:

```
{
  "version": "2017-02-28",
  "operation": "UpdateItem",
  "key": {
    "id": $util.dynamodb.toDynamoDBJson($ctx.args.input.id)
  },
  "update": {
    "expression": "SET #closed = :rightNow, #updatedAt = :rightNow",
    "expressionNames": {
      "#closed": "closed",
      "#updatedAt": "updatedAt"
    },
    "expressionValues": {
      ":rightNow": $util.dynamodb.toDynamoDBJson($util.time.nowEpochMilliSeconds())
    },
  },
  "condition": {
    "expression" : "secondaryId = :secondaryId AND (createdAt + 432000000) < :atThisMoment",
    "expressionValues" : {
      ":secondaryId": $util.dynamodb.toDynamoDBJson($ctx.args.input.secondaryId),
      ":atThisMoment": $util.dynamodb.toDynamoDBJson($util.time.nowEpochMilliSeconds())
    },
    "returnValuesOnConditionCheckFailure": false
  }
}
```

Can you point me to the right direction?
Thanks and Greetings

**Comment by tinnou** [comment]
The `returnValuesOnConditionCheckFailure` attribute is only available in DynamoDB TransactWriteItem Operations. 

If you use the `2018-05-29` template you can actually catch the error in your response mapping template and decide whether you want to swallow it, fallback to another item, or re-raise the error.  More details here https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-changelog.html#aws-appsync-resolver-mapping-template-version-2018-05-29

**Comment by zolcsi** [comment]
Thank you, all clear!
