### ISSUE TITLE
Long schema locking up Console

### ISSUE THREAD

**Issue by davekiss** [aws/aws-appsync-community#112]
Hi, my GraphQL Schema is about 3300 lines long and any time I visit the Schema tab of the Appsync Console, the Cloud9 editor locks up and my browser tab freezes.

Is there any way to increase performance of this page, or prevent the editor from loading the schema on page load? I'm frequently trying to view the resolvers instead of the schema editor, but I cannot navigate to them because the browser tab locks up.

Thanks in advance

**Comment by jtkirk-1** [comment]
I use AWS CDK.  It has been very helpful when I had to make updates to the resolvers.  Each deployment takes some time but I can make changes very easily.

If you bookmark your resolver or type the URL directly, does it still try to load the schema?  For me, it loads very quickly but my schema is not big.

https://console.aws.amazon.com/appsync/home?region=us#/ccoyzu/v1/schema **/Mutation/addUser/resolver**

Bold parts: 
- Mutation is either Mutation or Query
- addUser is your field name
- resolver is always resolver

**Comment by jpignata** [comment]
We made some performance fixes here to improve the performance of the console with large schemas. Please post here if you're still seeing issues like this!
