### ISSUE TITLE
Should AppSync with Aurora Serverless in the new regions that were recently released?

### ISSUE THREAD

**Issue by ration** [aws/aws-appsync-community#118]
Basically the issue in [in this so](https://stackoverflow.com/questions/62276299/appsync-data-api-is-not-available-in-this-region). I'm trying to enable the Data Source in a Auora Serverless database running in eu-central-1 but Appsync says:

```shell
$ aws appsync create-data-source --type RELATIONAL_DATABASE \ 
--api-id <id> --name "aurora-test" --relational-database-config \
"relationalDatabaseSourceType=RDS_HTTP_ENDPOINT,rdsHttpEndpointConfig={awsRegion=eu-central-1,dbClusterIdentifier=<MYDBARN>,databaseName=dbname,schema=public,awsSecretStoreArn=<STOREARN>}" --service-role-arn "<SERVICEARN>"

An error occurred (BadRequestException) when calling the CreateDataSource operation: The Data API is not available in this region.
```

If I look at my aurora serverless instance it says that `"HttpEndpointEnabled": true`

**Comment by jpignata** [comment]
Thanks, @ration. Yes, this should work in eu-central-1. Please let me know if you still see this behavior.
