### ISSUE TITLE
Intermittent Subscription Error

### ISSUE THREAD

**Issue by cthomaschase** [aws/aws-appsync-community#120]
Hi,

Around 5:00pm PT (Los Angeles) on 2020-06-16, we began receiving this error on subscriptions. Prior to this, the codebase was quite stable and subscriptions had been working well for months.

`Found 1 problem(s) with the schema: There is no type resolver defined for interface / union...`

Our schema seemed fine and we were unable to find the root cause.

Sometime in the early morning hours today (2020-06-18) we noticed the errors messages were no longer present and the subscriptions began working properly again.

Was there any issue on the AWS side that would confirm what we saw?

Thanks.

**Comment by itrestian** [comment]
Yes, there was a temporary issue with subscriptions during that time frame that is resolved now.

**Comment by cthomaschase** [comment]
Was there any indication of this in AppSync or elsewhere in AWS that would have helped us understand there was a problem within the service?
