### ISSUE TITLE
Feature Request: Caching responses

### ISSUE THREAD

**Issue by bboure** [aws/aws-appsync-community#13]
It would be great to be able to cache responses from response mapping templates.
The way it could work is that AppSync caches the request-response pair. For any subsequent identical request, AppSync would serve the cached response.

It would be useful, for example, if you have a query executing a lambda which executes heavy calculations. The second time, the result could just be returned from cache. This would even save money since the lambda does not even have to run.
It should work with any data source type. There are many advantages. For example, with `HTTP`, you would save round trips with the remote server (and possibly avoid throttling), with `DynamoDb`, save throughput, etc.

Maybe a way to do it would be to have a new `ElasticCache` Data Source, which would call another Data Source to resolve the value initially or serve the cached value?

**Comment by jbailey2010** [comment]
Hi,

Thanks for the feedback! This is a request we've heard before, and I'll note this as a +1 to prioritizing it for a future release.

Thanks,
Jeff

**Comment by awsed** [comment]
Cache support was just released today: https://aws.amazon.com/blogs/mobile/appsync-caching-transactions/
