### ISSUE TITLE
Pulumi AppSync Modules

### ISSUE THREAD

**Issue by cobraz** [aws/aws-appsync-community#131]
Hello!

Some time ago, I made [Pulumi AppSync Modules](https://github.com/bjerkio/pulumi-appsync-modules). It is inspired by [GraphQL Modules](https://graphql-modules.com) by [@UriGoldshtein](https://twitter.com/UriGoldshtein). It uses [Pulumi](https://pulumi.com) (*Modern Infrastructure as Code* tool) to deploy modulized GraphQL APIs to [AWS AppSync](https://aws.amazon.com/appsync/).

I'm wondering if you wound accept adding it to the list? I sure appreciate getting some more users!

**Comment by jpignata** [comment]
Sure! Feel free to open a PR. Thank you.

**Comment by cobraz** [comment]
Thanks! Done, #166
