### ISSUE TITLE
Projection Expression(s) available in AppSync Resolver Mapping Templates for DynamoDB 

### ISSUE THREAD

**Issue by NickLiffen** [aws/aws-appsync-community#138]
Hey 👋 

Is there any reason we can't limit the attributes to custom attributes vs `ALL_ATTRIBUTES` & `ALL_PROJECTED_ATTRIBUTES`. 

Let's say we store the following data:
```
{
"id": "uid",
"fname": "foo",
"lname": "bar",
"dob: "timestamp"
}
{
"id": "uid",
"fname": "fooOne",
"lname": "barOne",
"dob: "timestampOne"
}
{
"id": "uid",
"fname": "fooOne",
"lname": "barOne",
"dob: "timestampOne"
}
```

We have the needed primary index as `id` and let's say have a GSI of `fname` the key and `lname` as the sort key. 

However, I want to run a query that returns ALL DOB's. Is there no way where i could use [projection expressions](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ProjectionExpressions.html) to only limit the fields returned by the DB to just be DOB? 

Now, I know we could have a GraphQL Query for ALL users and the user could just specify in their query to return the `dob` field (the value of GRaphQL I know). The example I am using is just an dummy, we have a use case where we only need to return one value from a record. Projection Expressions seem to be a good way of doing this, just wondered what the best process would be for this.

**Comment by ahmadizm** [comment]
Hi, I think in the absence of Project Expressions, your own suggestion of a query with only `dob` seems to be your best bet.

**Comment by harish1454** [comment]
Hello, apologies for the delay in providing support for DynamoDB projection expressions. We recently launched this feature. Please find the below blog post which contains references to document changes and examples.
https://aws.amazon.com/blogs/mobile/aws-appsync-now-supports-projection-expressions-in-dynamodb-resolvers/
