### ISSUE TITLE
Feature request: DynamoDB transaction support in AppSync resolvers 

### ISSUE THREAD

**Issue by appwiz** [aws/aws-appsync-community#14]
Requested on [StackOverflow](https://stackoverflow.com/q/54081723/137598).

Recently, AWS announced [DynamoDB Support for Transactions](https://aws.amazon.com/about-aws/whats-new/2018/11/announcing-amazon-dynamodb-support-for-transactions/). We should expand the DynamoDB resolvers in AppSync to support these actions.

**Comment by packerfan626** [comment]
+1, this would be insanely helpful.

**Comment by bennairn** [comment]
+1

**Comment by lenarmazitov** [comment]
+1

**Comment by KazuyaUesato** [comment]
+1

**Comment by kntaka** [comment]
+1

**Comment by gins0023** [comment]
+1

**Comment by psiqueir** [comment]
Any updates on whether this will be in the roadmap in the near future?

**Comment by d-w4lsh** [comment]
+1

**Comment by andrealascola-docebo** [comment]
+1
this feature would be very useful to us, hope to get some update soon

**Comment by andrealascola-docebo** [comment]
+1
this feature can be very useful for us, hope to get updates soon on that

**Comment by sevees** [comment]
+1

**Comment by awsed** [comment]
Transactions support was just released today: https://aws.amazon.com/blogs/mobile/appsync-caching-transactions/
