### ISSUE TITLE
AppSync Mutation sometimes taking about 5s or more

### ISSUE THREAD

**Issue by devbhullar** [aws/aws-appsync-community#140]
I'm calling a mutation from my lambda function, the average response time for this mutation is < 100ms. However, I've seen instances where the mutation has taken up-to 52s. 

Here is a trace from AWS X-Ray that shows the mutation took 5s. It looks like the resolver itself takes 1ms but the API takes 5s, why is it taking so long?

![image](https://user-images.githubusercontent.com/29358001/99729674-1b709980-2a70-11eb-87c3-24df55572ecd.png)

**Comment by Ricardo1980** [comment]
Are you using Aurora Serverless?

**Comment by devbhullar** [comment]
@Ricardo1980 No, this mutation is not tied to any database calls. It's just for an AppSync subscription. I'm using DynamoDB for other mutations in my AppSync API.

**Comment by zevmo** [comment]
Is it a Lambda? If this is not a consistent condition, it may be the standard warm-up issue.

**Comment by devbhullar** [comment]
@zevmo It doesn't look like a Lambda warm-up issue to me because X-Ray shows that they API request itself took 5s.

**Comment by jpignata** [comment]
Hi @devbhullar -- this one is quite stale so wanted to check in. Are you still seeing this issue? Feel free to email me if so, so we can dig into it.
