### ISSUE TITLE
How can I get a portion of selectionSetGraphQL

### ISSUE THREAD

**Issue by alexboulay** [aws/aws-appsync-community#143]
I have this selection set I am sending to my Lambda resolver:

```
{
  recommendationId
  items {
    id
    name
  }
}
```

However, inside my resolver, i need to call a graphql api with a subset of this selection set.

How can I then get this:
```
{
   id
   name
}
```

**Comment by bboure** [comment]
@alexboulay You should be able to parse the selectionSet using [graphql-js](https://github.com/graphql/graphql-js/blob/master/src/language/parser.js#L112)
Then, you can explore the tree for the part that you are interested in and call [print](https://github.com/graphql/graphql-js/blob/master/src/language/printer.js#L10) to transform it back into a string.

Be aware though that if you use Fragments, you [won't get anything under them](https://github.com/aws/aws-appsync-community/issues/142)

**Comment by alexboulay** [comment]
@bboure Thank you, I got it working with this piece of code:

```javascript
const { parse, print } = require("graphql/language")

const document = parse('{ id items {id name} }')

const subSet = document
  .definitions[0]
  .selectionSet
  .selections
  .find(elem => elem.name.value == 'items')

print(subSet) // => `items {id name}`
```

**Comment by bravoy93** [comment]
Hi, I've a similar case as @alexboulay but the target of the gql request is another apssync API. Does anyone know how I can send a subselect of selectionSetGraphQL  from my first API to the target API?

**Comment by bravoy93** [comment]
UPDATE of solution I've found. For the case of @alexboulay it will be:

`
#set( $subselection = "" )
#foreach( $selectionField in $context.info.selectionSetList )
    #if( $util.matches("items/\w+", $selectionField ))
  	  #set( $subselection = "$subselection ${selectionField}")
    #end
#end

## It replaces the preffix for a new line start (\n), this is optional, it could be any spacing char, the actually goal is to remove the preffix
#set( $subselection = $util.str.toReplace($subselection , "items/", "\u000A") )

## Build the query
#set( $query = "<gql operation> <operation name | undefined>($input: <input type>) {
	<operation name>(input: <input type>) { $subselection }
}
")`

The object `$context.info.selectionSetList` is an array that contains all of the fields and sub fields, for this example it will be:
`
[
  "recommendationId",
  "items",
   "items/id",
   "items/name"
]
`
