### ISSUE TITLE
Data missing : AppSync List limit limits the amount of elements checked in database, instead of amount of results thrown. Bug or Scam?

### ISSUE THREAD

**Issue by vincent38wargnier** [aws/aws-appsync-community#156]
Hi everyone,

here is my super easy bug :
I want to get element by Id using list.
If i do a get query, it works, but with list query, it returns me [] until I increase the limit to max size.

Is this logic logic ?
Check below the image to understand clearly please :

![image](https://user-images.githubusercontent.com/33725800/110922863-847e6480-8320-11eb-95ed-6e5c914bb75b.png)
So as you can see the list is not reading all the elements of the table. 

Why? The limit is supposed to tell how many results we wants right? Not how many elements we want to check randomly in the database. Well if I'm wrong, then I don't know who needs to read n random element in his database.

And if setting the limit to max size is the solution, does it mean that I have to add limit: 999999999 everywhere in my code where I use a list? (More or less all my queries have nested lists, so more than 500 different peaces of my code to change? it sounds like aws trolled me one more time)

**Is there a way to set default limit to infinity?**
Thank you by advance !

**Comment by vincent38wargnier** [comment]
Sorry this is a duplicate, but hey, I figured out what all this is like that, check that out : https://github.com/aws-amplify/amplify-js/issues/2233#issuecomment-798772678

**Comment by MuhammadAbdullah54321** [comment]
From what I have learned trying many different ways is that even if you increase the limit it still do not returns all the elements that match the filter.
The way around i found is that you have to use 'nextToken' to get the chunk of remaining and then do api call with its 'nextToken' to get the chunk of remaining and so on .....

For example::
I have total 7126 elements in DynamoDB
Out of which I have 144 elements in DynamoDB table that meets a filter condition and I have set limit to 10000 but it still returns me just 20 elements. 
So when I uses "nextToken" to retrieve more it still returns around 20 elements.

Either I am doing something wrong 
OR
This behaviour is really out of this world

**Comment by buggy** [comment]
@MuhammadAbdullah54321 While I can explain the problem it won't help. When you make that request most people expect it to "Search for X and return the first N rows" (limit the result) but DynamoDB (the backend database) treats this is as "Search the first N rows for X" (limits the rows searched). If X doesn't occur in the first N rows you get zero results and you're told there are more results.
