### ISSUE TITLE
ExpressionValues are merged if operation has several

### ISSUE THREAD

**Issue by kyptov** [aws/aws-appsync-community#162]
PutItem, UpdateItem, and DeleteItem operations allows to use expressionValues in operation object and in condition. If the same placeholder is used, it will be merged silently.

```{
  "version": "2018-05-29",
  "operation": "UpdateItem",
  "key": {
    "id": {"S": "SOME_ID"}
  },
  "update": {
    "expression": "SET field = :value",
    "expressionValues": {
      ":value": {"S": "VALUE"}
    }
  },
  "condition": {
    "expression": "field = :value",
    "expressionValues": {
      ":value": {"NULL": null}
    }
  }
}
```

In this example I expect to update item`s *field* with VALUE only if *field* is already null. 

I used `:value` placeholder for both expressionValues and found out that my first ` ":value": {"S": "VALUE"}` was replaced by `":value": {"NULL": null}`

**Comment by alextriaca** [comment]
Just got hit by this too. Feels like these values should be scoped or at least raise a warning/exception when you have duplicates.

**Comment by ndejaco2** [comment]
We have added an exception for this issue when it occurs so that duplicates are not allowed.
