### ISSUE TITLE
App sync query filters are returning an empty array

### ISSUE THREAD

**Issue by reberthkss** [aws/aws-appsync-community#165]
### Description
I've trouble executing queries with filters in App Sync. The weird behavior is that data I wanna get exists in DynamoDB and I can get them using the Item Explorer feature but using app sync query not. 

The below images describes the current behavior.

### Pictures

![image](https://user-images.githubusercontent.com/54030471/120105905-3283f880-c131-11eb-9ca7-ea0e57ab75c2.png)
![image](https://user-images.githubusercontent.com/54030471/120105912-3748ac80-c131-11eb-8457-f68e5592d7bd.png)

**Comment by reberthkss** [comment]
additional: event filter to id returns a empty array.

**Comment by buggy** [comment]
This is expected.

DynamoDB applies the limit first (limiting the number of rows searched) then the filter. You're basically saying "Grab the first 10 rows in the database and return those that match this filter". If you remove the limit you'll probably get some results but ultimately you're going to hit the 1MB data limit.

The only solution is to implement paging.

Also, if you're doing a lot of searching by category ID then I would strongly recommend setting up an index on that field and using a DynamoDB query instead of scan. It will be faster and save you money.

**Comment by reberthkss** [comment]
Hey @buggy ! Thanks you for reply.  

Yesterday I spent a lot of time thinking about how to implement a query to get the products by a category id. The categories and products are in different tables and at the first moment I wondering load the products using a relation one-to-many but I get struggled with pagination (how paginate the products returned?) like this query below.

```
query productsById($id: String) {
     listCategories(id: $id) {  <------ autogenerated by amplify
          name
          products {
                 id
                 name
                 price
          }
     }
}
```


with the follow schemas:

```
@model
@key(name="byCategory", field=["categoryId"])
type Product {
    id: ID!
    categoryId: ID!
    name: String!
    price: Float!
}
```

```
@model()
type Department {
   id: ID!
   name: String!
   products: [Products] @connection(key="byCategory", fields=["id"])
}
```
After this trouble, I think on use `BatchGetItem` to get a list of products using a hard-coded filter. Unfortunately, I had trouble debugging the error informing me that `@version` field was not found. The Request Resource Map was like this:

```
#set( $limit = $util.defaultIfNull($context.args.limit, 100) )
#set( $ListRequest = {
  "version": "2018-05-29",
  "limit": $limit
} )
#if( $context.args.nextToken )
  #set( $ListRequest.nextToken = $context.args.nextToken )
#end
#if( $context.args.filter )                                                                                                              \/ start here     
  #set( $ListRequest.filter = $util.parseJson("$util.transform.toDynamoDBFilterExpression({'filter': {'categoryId': {'eq': 
                                      \/ end here
$ctx.args.categoryId}}})") )
#end
#if( !$util.isNull($modelQueryExpression)
                        && !$util.isNullOrEmpty($modelQueryExpression.expression) )
  $util.qr($ListRequest.put("operation", "Query"))
  $util.qr($ListRequest.put("query", $modelQueryExpression))
  #if( !$util.isNull($ctx.args.sortDirection) && $ctx.args.sortDirection == "DESC" )
    #set( $ListRequest.scanIndexForward = false )
  #else
    #set( $ListRequest.scanIndexForward = true )
  #end
#else
  $util.qr($ListRequest.put("operation", "Scan"))
#end
$util.toJson($ListRequest)
````
This Request Mapping Template was a copy of the auto-generated `listProducts` query. 

After many overthinking, I decided to get the products using the auto-generated query by amplify, e.g. `listProducts` and apply a filter for `categoryId` and use the in-built pagination resource.

Now I in a doubt about which of those approaches should I follow.

**Comment by buggy** [comment]
Unfortunately I can't really help with Amplify generated resolvers because I write my resolvers by hand instead of generating them from the schema.

**Comment by reberthkss** [comment]
Can you share the requesting resolver for the mentioned use case by you? (With query instead scan)

**Comment by reberthkss** [comment]
Closing this because I decided to use the relation between `category` and `products` approach:

```
schema.graphql
@model()
type Department {
   id: ID!
   name: String!
   products: [Products] @connection(key="byCategory", fields=["id"])
}
```

```
query LoadProductsOfCategory($categoryId: String!, $nextPage: String) {
               loadDepartment(id: $categoryId) {
                      products (nextToken: $nextPage){
                               items {
                                    name
                               }
                      }
               }
}
```
