### ISSUE TITLE
Push fails after updating API authorization type 

### ISSUE THREAD

**Issue by JosephVasse** [aws/aws-appsync-community#167]
Hello, 

I'm facing an issue using Amplify AppSync. 

I used to authenticate in my Api using API_KEY, but now that my project is getting bigger I have to start thinking about Security. 
So I changed my API auth mode from APIkey to CognitoUserGroups. 
(using the Cli & amplify update api ...) 

But whenever I try to push my backend after this modification, it results with a fail with the following error : 

`UPDATE_FAILED      authvilleoamplify5f4XXXX   AWS::CloudFormation::Stack Thu Jun 17 2021 08:57:17 GMT+0200 (heure d’été d’Europe centrale) [/Resources/UserPool/Type/LambdaConfig] 'null' values are not allowed in templates
...

UPDATE_FAILED               authuserPoolGroups                     AWS::CloudFormation::Stack Thu Jun 17 2021 08:57:28 GMT+0200 (heure d’été d’Europe centrale) Resource update cancelled   `

I searched in the entire project and I'm not able to find the origin of this issue ... I would really appreciate some help there ! 

Additionnal infos : 
  Enabled categories: 
      Api       
      Auth
      Storage
      Function 
      Analytics
  amplify version : amplify 4.51.4

**Comment by jpignata** [comment]
Are you using the Amplify CLI? If so, your best bet would likely be to open an issue here: https://github.com/aws-amplify/amplify-cli
