### ISSUE TITLE
"npm install --save aws-appsync" fails 

### ISSUE THREAD

**Issue by julie777** [aws/aws-appsync-community#174]
After creating a quasar vue project the install of aws-appsync fails with the following error.

npm install --save aws-appsync
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: quasar-demo@0.0.1
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.8" from @react-native-community/async-storage@1.12.1
npm ERR!   node_modules/@react-native-community/async-storage
npm ERR!     peer @react-native-community/async-storage@"^1.11.0" from aws-appsync@4.1.0
npm ERR!     node_modules/aws-appsync
npm ERR!       aws-appsync@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-native@0.64.2
npm ERR! node_modules/react-native
npm ERR!   peer react-native@">=0.59" from @react-native-community/async-storage@1.12.1
npm ERR!   node_modules/@react-native-community/async-storage
npm ERR!     peer @react-native-community/async-storage@"^1.11.0" from aws-appsync@4.1.0
npm ERR!     node_modules/aws-appsync
npm ERR!       aws-appsync@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\julie\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\julie\AppData\Local\npm-cache\_logs

[2021-07-17T17_14_44_782Z-debug.log](https://github.com/aws/aws-appsync-community/files/6835056/2021-07-17T17_14_44_782Z-debug.log)

**Comment by jpignata** [comment]
Heya! It might be best to create this issue in the https://github.com/awslabs/aws-mobile-appsync-sdk-js repository.
