### ISSUE TITLE
GSI with composite sort key doesn't get populated 

### ISSUE THREAD

**Issue by rezab777** [aws/aws-appsync-community#181]
Hi,

I have a GSI (videosByCustomer) with a composite sort key, but it isn't being populated in DynamoDB. Both fields of the composite sort key exist in the table and are populated. AWS support suggested I manually create a camera_id#video_datetime field in DynamoDB otherwise it would not be created automatically. Is this really best practice ? And why does not AppSync provide that functionality already ?

```
type Video
  @model
  @key(fields: ["owner", "video_datetime", "camera_id"]) # Composite PK
  # GSIs
  @key(
    name: "videosByCustomer"
    fields: ["customer_id", "camera_id", "video_datetime"]
    queryField: "videosByCustomer"
  ) {
  id: ID!
  owner: ID! 
  customer_id: ID! 
  camera_id: ID! 
  # Fields
  video_datetime: String!
  customer: Customer @connection(fields: ["customer_id"])
}
```

**Comment by jpignata** [comment]
Heya! The Amplify CLI just shipped a new version of the GraphQL transformer with improved key syntax. Let me know if this helps: https://aws.amazon.com/blogs/mobile/aws-amplify-announces-the-new-graphql-transformer-v2-more-feature-rich-flexible-and-extensible/
