### ISSUE TITLE
Long running processes fail after a few hours

### ISSUE THREAD

**Issue by slikk66** [aws/aws-appsync-community#188]
Hi folks, this is driving me crazy.  I have some long running processes in ECS that are listening for messages coming in from SQS and then query my Appsync API as needed.

After a few hours, it starts failing with 403 error.  The containers start up again, and fail again.  If I destroy them and then recreate them, they work again for a while.  It seems to be something to do with the credentials expiring, but I'm using the `AWS.CredentialProviderChain()` object to get the credentials, and the role of the ECS task has permissions to query the API.  So why does it fail after a while?  

Here's my code, if anyone sees anything please let me know or suggest a workaround, I'd really appreciate it:

The code fails when calling my `querySite` function which in turn calls `getAppSyncClient` to get a fresh client each time:

`querySite`
````
            let the_client = await new getAppSyncClient().parse();
            let query_data: any = await the_client.query({
                query: gql(getSite),
                variables: {
                    id: site_id,
                },
                fetchPolicy: "network-only",
            });
            if (query_data.data.getSite) {
                return query_data.data.getSite as Site;
            }
````

`getAppSyncClient`
````
import AWS from "aws-sdk";
import AWSAppSyncClient from "aws-appsync";

const region = process.env.AWS_REGION;
const endpoint = process.env.GRAPHQL_ENDPOINT;

export default class getAppSyncClient {
    constructor() {
        console.log("getAppSyncClient() INIT");
    }

    private async getCredentials() {
        let x = new AWS.CredentialProviderChain();
        return x.resolvePromise();
    }

    public async parse() {
        console.log("return AWSAppSyncClient()");
        let client = new AWSAppSyncClient({
            url: endpoint!,
            region: region!,
            auth: {
                type: "AWS_IAM",
                credentials: () => this.getCredentials(),
            },
            disableOffline: true,
        });

        let the_client = await client.hydrated();

        return the_client;
    }
}
````

The v2 AWSAppSyncClient seems to require an Auth object, which seems weird as it should resolve the credentials using the built in AWS sdk I'd imagine like everything else, but it does seem I need to pass them in like this.

I was looking at the v3 docs, and it seems like that may be correct there, but honestly I can't follow those docs on how to do a simple query against an API.. if that turns out to be the best route, I can give it a shot.

Thanks!

**Comment by slikk66** [comment]
I may have found it.  It seems that my containers on ECS have both env vars AWS_ACCESS_KEY etc and also the local URI for getting credentials from the Fargate system.

I did a `console.log(process.env)` and see the following:

````
{
    "LANG": "en_US.UTF-8",
    "TZ": ":/etc/localtime",
    "PATH": "/opt/pulumi/bin:/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin",
    "LD_LIBRARY_PATH": "/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib",
    "LAMBDA_TASK_ROOT": "/var/task",
    "LAMBDA_RUNTIME_DIR": "/var/runtime",
    "AWS_ACCESS_KEY_ID": "ASIATW....",
    "AWS_SECRET_ACCESS_KEY": "111111Ir2bU0....",
    "AWS_SESSION_TOKEN": "IQoJb3JpZ2luX2VjECEaCXVzLXdlc3Q.....",
    "AWS_DEFAULT_REGION": "us-west-2",
    "AWS_CONTAINER_CREDENTIALS_RELATIVE_URI": "/v2/credentials/800e763b-d3f5-4cbf-bbc7-11111111111",
    "AWS_EXECUTION_ENV": "AWS_ECS_FARGATE",
    "AWS_REGION": "us-west-2",
    "ECS_CONTAINER_METADATA_URI_V4": "http://169.254.170.2/v4/AAAAAAAAAAA40de93665e75424605c5-111111111111",
    "ENV": "prod",
    "HOSTNAME": "ip-10-66-8-156.us-west-2.compute.internal",
    "ECS_CONTAINER_METADATA_URI": "http://169.254.170.2/v3/AAAAAAAAAAA40de93665e75424605c5-11111111111",
    "HOME": "/root"
}
````

Im guessing that the ENV vars were overwriting the ECS style container variables.  I replaced all of my `import AWS from "aws-sdk"` to use this:

`import AWS from "./getAwsClient";`

and in there I have:

````
import AWS from "aws-sdk";
console.log(JSON.stringify(process.env));
if (process.env.AWS_CONTAINER_CREDENTIALS_RELATIVE_URI) {
    console.log("ECS container mode! modifying provider to remove ENV");
    AWS.CredentialProviderChain.defaultProviders = [
        function () {
            return new AWS.ECSCredentials();
        },
        function () {
            return new AWS.ProcessCredentials();
        },
        function () {
            return new AWS.TokenFileWebIdentityCredentials();
        },
        function () {
            return new AWS.EC2MetadataCredentials();
        },
    ];
}

export default AWS;
````

which will remove the ENV VAR pulls from the credential chain, making it look for deeper credentials (like ECS url).  I just ran it and now see this:

````
return AWSAppSyncClient()
--
RemoteCredentials {
expired: false,
expireTime: 2021-11-20T04:43:42.000Z,
refreshCallbacks: [],
accessKeyId: 'ASIATWC....',
sessionToken: 'IQoJb3JpZ2luX2VjECc.....',
httpOptions: { timeout: 1000 }
}
````

notice "RemoteCredentials", previously I was getting:

````
return AWSAppSyncClient()
--
EnvironmentCredentials {
expired: false,
expireTime: null,
refreshCallbacks: [],
accessKeyId: 'ASIATWCU....',
sessionToken: 'IQoJb3JpZ2luX2VjEC....',
envPrefix: 'AWS'
}
````

notice "EnvironmentCredentials"... I'll let this run overnight and see if it works

**Comment by jpignata** [comment]
That looks like a bingo to me. The environment variables would be used before the container credentials fetched via the metadata service.
