### ISSUE TITLE
Resolver caching key using all the arguments

### ISSUE THREAD

**Issue by bboure** [aws/aws-appsync-community#194]
By default, the caching key is the combination of `$context.arguments`, `$context.identity` and `$context.source`.
My use case is simple, I want to cache the resolver based on `$context.arguments` **only**.  ([See doc](https://docs.aws.amazon.com/appsync/latest/devguide/enabling-caching.html))

I tried setting the `cachingKey` to `$context.arguments`, but I am getting the following error from CloudFormation:

![image](https://user-images.githubusercontent.com/7089997/146787132-11d2fefc-b0cc-4f63-af9b-b3bae757811f.png)

It looks like AppSync is expecting a subset of the maps but not the map themselves.

Obviously, the workaround is to set all the attributes manually:
- `$context.arguments.id`
- `$context.arguments.filters`
- etc

but it should be simpler. It is also one more thing to maintain if the arguments change.

`$context.arguments`, `$context.identity` and `$context.source` should be accepted as a whole separately.

**Comment by ndejaco2** [comment]
You also can now evict using the $util.evictFromApiCache utility using these top level objects.
