### ISSUE TITLE
AWS appsync subscription fails to connect

### ISSUE THREAD

**Issue by japatki** [aws/aws-appsync-community#195]
I am trying to connect subscription as per:-
https://docs.aws.amazon.com/appsync/latest/devguide/real-time-websocket-client.html

Postman:-
![image](https://user-images.githubusercontent.com/96426597/146773041-7982c7bf-6629-4ab2-9385-9d4ab0f8c189.png)

I get the error:-

{
    "payload": {
        "errors": [
            {
                "message": "NoProtocolError",
                "errorCode": 400
            }
        ]
    },
    "type": "connection_error"
}

Why does it happen ?

**Comment by Sunac** [comment]
Didn't tried with Postman as I'm successfully using Altair for AppSync including its subscriptions: https://altair.sirmuel.design/docs/features/graphql-subscriptions.html.
If it's just about testing.

**Comment by Sunac** [comment]
I just tried succeeded with Postman and here's what else you need to configure as well:

In the Headers (you'll see 6 hidden)
add this one:
`Sec-WebSocket-Protocol:graphql-ws`

In your parameters to achieve connection pass as documented:
`payload: e30=` - which is empty {}
`header: {base64}`  - base64 of {"host":"YOUR_ID.appsync-api.eu-west-1.amazonaws.com","x-api-key":"YOUR KEY"}
Connect now.
You'll first get a response:
`Connected to wss:....`
Then:
`{
    "type": "ka"
}`

After that, you need to send a message with unique id and your subscription check from [there](https://docs.aws.amazon.com/appsync/latest/devguide/real-time-websocket-client.html#connection-acknowledge-message)
`{"id":"some","payload":{"data":"{\"query\":\"subscription Some{\\n  onEvent{\\n    getSomething{\\n      something{\\n        track{\\n          title\\n        }\\n      }\\n    }\\n  }\\n}\",\"variables\":null}","extensions":{"authorization":{"x-api-key":"KEY","host":"YOUR HOST"}}},"type":"start"}`

After that you'll get 
`{"id":"******e","type":"start_ack"}`

And start receiving messages :)

It's all basically documented but maybe not so clear. Perhaps it could be successful with less info sent in your payload, but this is something that worked out initially for me as you can see:

![image](https://user-images.githubusercontent.com/15103463/146821046-2c8af522-02ce-4288-992d-63feb719acea.png)

As mentioned, I use Altair for this so you can play around with this more, but this is working for a start :)

**Comment by japatki** [comment]
Awesome ! Worked for me. . thanks Sunac.. on another note, do you know how i could extract Curl from postman for a websocket request ?

**Comment by japatki** [comment]
Thanks Sunac! Worked for me as well :)

**Comment by Sunac** [comment]
@japatki you're welcome :)

**Comment by JinapriyaM** [comment]
How to add this header to WebSocket client in react?

**Comment by huytb-pionero** [comment]
@Sunac  thankyou very much, you saved my life !!!!
