### ISSUE TITLE
DynamoDB tables crashing and hanging, even after many changes

### ISSUE THREAD

**Issue by clarkfwhite** [aws/aws-appsync-community#199]
Hello,

I've modified my tables and restarted from scratch numerous times, and they've always had issues. Often, it causes the Amplify CI and/or the Amplify Studio GUI to to hang or crash.

One of the three tables began to become too large for Amplify. Recently, I broke it down into sub-tables, while updating it to the V2 decorators. Since then, it's become especially unstable.

https://github.com/aws-amplify/amplify-adminui/issues/412

Would you mind taking a look at it, please? Thanks for your time.

**Comment by clarkfwhite** [comment]
Bump

**Comment by onlybakam** [comment]
ref: https://github.com/aws-amplify/amplify-studio/issues/412

closing since this is an Amplify Studio issue
