### ISSUE TITLE
Remove alg parameter as required for OPENID_CONNECT Authorization

### ISSUE THREAD

**Issue by joshjones95** [aws/aws-appsync-community#201]
Looking at the standards for JSON Web Keys, the alg parameter is determined to be optional (https://datatracker.ietf.org/doc/html/rfc7517#section-4.4). However it is required as part of AppSync's specification (https://docs.aws.amazon.com/appsync/latest/devguide/security-authz.html#openid-connect-authorization). 

This is currently blocking Authorization for IdP's such as Azure AD and Azure AD B2C as part of its JWKS_URI they provide kty and kid

**Comment by maxblu** [comment]
Nothing on this?

**Comment by maxblu** [comment]
Appsync work well now with Azure AD the only thing is that the issuer url must be https://login.microsoftonline.com/{tenan-id}/v2.0
and the token to send must be id_token
