### ISSUE TITLE
Per resolver caching - exclude identity

### ISSUE THREAD

**Issue by asyschikov** [aws/aws-appsync-community#207]
So by default resolver caching uses $context.arguments , $context.source , and $context.identity as a composite key for a cache entry. We have a lot of content that is not personalised (most of it actually), so I don't want identity to be part of the key because it will just duplicate same cache entries per user (Question#1: is it really the case?). So I decided to set the following cache keys: `'$context.arguments', '$context.source'` and it doesn't work failing with the error:

> Caching keys need to start with $context.args, $context.arguments, $context.identity, or $context.source. 

So it seems that only specific fields are supported like `$context.arguments.something`. But I don't want to list every input for every resolver... So my question is there a way to do something like `$context.arguments.*` maybe?

**Comment by asyschikov** [comment]
@ndejaco2 thanks, that's it, I am closing the issue.

**Comment by SchollSimon** [comment]
The current behaviour of cachingKey configuration is still a pain. I reported months ago an issue which was basically ignored until now so reopening this ticket here as it is somehow related.
@asyschikov please have a look https://github.com/aws/aws-cdk/issues/20773.
