### ISSUE TITLE
How do we handle errors? appsync function lambda

### ISSUE THREAD

**Issue by light320180** [aws/aws-appsync-community#209]
How do we properly pass errors? Right now, all errors are returning as "Lambda:Unhandled".

Any way to customize errorType, errorInfo?

{
  "data": null,
  "errors": [
    {
      "path": [
        "updateProject"
      ],
      "data": null,
      "errorType": "Lambda:Unhandled",
      "errorInfo": null,
      "locations": [
        {
          "line": 15,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Parameter cannot be empty"
    }
  ]
}

I modified the error object, and clouwatch prints out the error message, but there is no way to return to the front end to be consistent with this error message. The value of errorType is fixed to "Lambda:Unhandled"
clouchwatch：
{
    "errorType": "catalog.1234",
    "errorMessage": "token error",
    "stack": [
        "Error: token error",
        "    at /var/task/index.js:1:7314181",
        "    at m (/var/task/index.js:1:369341)",
        "    at Generator._invoke (/var/task/index.js:1:369129)",
        "    at Generator.next (/var/task/index.js:1:369770)",
        "    at t (/var/task/index.js:1:259)",
        "    at n (/var/task/index.js:1:470)",
        "    at /var/task/index.js:1:529",
        "    at new Promise (<anonymous>)",
        "    at Runtime.<anonymous> (/var/task/index.js:1:410)",
        "    at Runtime.handler (/var/task/index.js:1:7314755)"
    ]
}

{
    "errorType": "Error",
    "errorMessage": "Parameter cannot be empty.",
    "type": "catalog.123",
    "stack": [
        "Error: Parameter cannot be empty.",
        "    at /var/task/index.js:1:7314202",
        "    at m (/var/task/index.js:1:369341)",
        "    at Generator._invoke (/var/task/index.js:1:369129)",
        "    at Generator.next (/var/task/index.js:1:369770)",
        "    at t (/var/task/index.js:1:259)",
        "    at n (/var/task/index.js:1:470)",
        "    at /var/task/index.js:1:529",
        "    at new Promise (<anonymous>)",
        "    at Runtime.<anonymous> (/var/task/index.js:1:410)",
        "    at Runtime.handler (/var/task/index.js:1:7314735)"
    ]
}

I have seen some answers to change the default resolver and then define the return myself, but I don't think this really solves the problem. Is this a bug of appsync? Or is there any other way I don't know, hope to get help, thanks.
**default resolver**
#if( $ctx.error )
  $util.error($ctx.error.message, $ctx.error.type)
#end
$util.toJson($ctx.result)

**change resolver**
#if( $context.result && $context.result.error_message )
    $util.error($context.result.error_message, $context.result.error_type, $context.result.error_data)
#else
    $util.toJson($context.result)
#end

Hope that helps, thanks a lot

**Comment by onlybakam** [comment]
Hello, we have information about working with Lambda data sources:
- https://docs.aws.amazon.com/appsync/latest/devguide/resolver-reference-lambda-js.html
- https://docs.aws.amazon.com/appsync/latest/devguide/direct-lambda-reference.html
- https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-lambda.html
