### ISSUE TITLE
AWS AppSync Query Sanbox - authorization provider IAM returns "Not Authorized"

### ISSUE THREAD

**Issue by Simon-PumpAndUp** [aws/aws-appsync-community#219]
Hello,

I've search for a while and I couldn't find a solution so here I am.

When I use the sandbox, in AWS AppSync using IAM as authorization provider to test my queries, it doesn't work:
<img width="1032" alt="Screenshot 2022-05-04 at 20 51 30" src="https://user-images.githubusercontent.com/97729760/166805472-10fef552-894c-49e2-a6bd-0e6f2f960174.png">

My model auth: 
@auth(rules: [
  { allow: owner },
  { allow: public, provider: iam },
  { allow: private, operations: [read] }
]) 

Whereas with a connected user it works (Cognito).  

I'm not sure how I'm supposed to set up this. 

Thank you :)

**Comment by Simon-PumpAndUp** [comment]
custom-roles.json

```
{
  "adminRoleNames": [
     "roleName",
     "root"
  ]
}
```

**Comment by undrash** [comment]
Why is this issue closed? What is the solution?

**Comment by undrash** [comment]
Thank you! This is what I was looking for from the docs:


## [Use IAM authorization within the AppSync console](https://docs.amplify.aws/cli/graphql/authorization-rules/#use-iam-authorization-within-the-appsync-console)

IAM-based `@auth` rules are scoped down to only work with Amplify-generated IAM roles. To access the GraphQL API with IAM authorization within your AppSync console, you need to explicitly allow list the IAM user's name by adding them to `amplify/backend/api/<your-api-name>/custom-roles.json.` (Create the `custom-roles.json` file if it doesn't exist). Append the adminRoleNames array with the IAM role or user names.

**Comment by cpinjala** [comment]
What if we have multiple AWS accounts into which we need to deploy our code. How can we create account specific custom-roles.json files
