### ISSUE TITLE
Bug: GraphQL subscriptions do not throw error on websocket failure

### ISSUE THREAD

**Issue by tylermakin** [aws/aws-appsync-community#22]
**Issue:** When subscribing to AppSync updates through AWS Amplify, `undefined` websocket errors do not invoke the `error` callback. *This occurs in browsers that support websockets when connected to networks that block or inhibit websocket connections, such as some proxies and corporate networks.*

**Expected Behavior:** When an error occurs such as a network disconnection, the `error` callback should be invoked.

**Experienced Behavior:** If a websocket is unable to connect and returns `undefined`, an error is logged in the console but the subscription's error callback is not invoked.

### Sample Code
```
API.graphql(
  graphqlOperation(subscriptions.mutatedItem, { item_id: item_id })
).subscribe({
  error: (err) => console.log("Network disconnected"),
  next: (eventData) => updateItems(eventData)
});
```

### Console
> paho-mqtt.js:1128 WebSocket connection to 'wss://**************-ats.iot.us-west-2.amazonaws.com/mqtt?...' failed: Error during WebSocket handshake: Unexpected response code: 400
> S._doConnect @ paho-mqtt.js:1128

> Uncaught (in promise)
> Object
> errorCode: 7
> errorMessage: "AMQJS0007E Socket error:undefined."
> invocationContext: undefined

**Comment by appwiz** [comment]
@tylermakin This issue is in the Amplify client. I see that you opened an issue in the Amplify repository hence I'm closing this issue in lieu of https://github.com/aws-amplify/amplify-js/issues/3212
