### ISSUE TITLE
VTL restrictions in Mapping Templates

### ISSUE THREAD

**Issue by reply2srij** [aws/aws-appsync-community#222]
Please update your documentation to list the unsupported features like #macro of VTL by AWS AppSync and API Gateway Mapping Templates. If this is already available, could you please send the link. 
Also, please share your plans for the following feature request: #90

**Comment by onlybakam** [comment]
Hello, AppSync does not support the `#macro` feature in VTL.
We have released JavaScript resolvers which makes it easier to write your business logic. You can find more information about JavaScript resolvers here: https://docs.aws.amazon.com/appsync/latest/devguide/resolver-reference-js-version.html
