### ISSUE TITLE
AppSync Sync Operation Query According To A Partition Key (PK)

### ISSUE THREAD

**Issue by Bariah96** [aws/aws-appsync-community#225]
The Appsync **Sync Operation** on a Dynamodb table with a single table design is **Too Slow** due to going through all the records accross partitions after a specific lastSync value, as far as we know there's no way currently that we can specify a partition key. we can only add a filter which results in the same slowness issue. 

We need the ability to query the sync table given the lastSync AND A PARTITON KEY for much more efficient querying, This may also imply having some control into what to put into the sync table as partition and secondary keys whenever a mutation is executed ..

**Comment by Wissam-Yelhow** [comment]
This feature would be really helpful!

**Comment by MohamedDarwiche-DaherSoftware** [comment]
Totally agree!
We need such feature to improve sync table querying

**Comment by jainkjohnson** [comment]
Its really helpful for querying the sync tables.

**Comment by AmenaSafa** [comment]
This is much needed

**Comment by onlybakam** [comment]
Hello, this is possible with `basePartitionKey`. See details about the syntax here: https://docs.aws.amazon.com/appsync/latest/devguide/js-resolver-reference-dynamodb.html#js-aws-appsync-resolver-reference-dynamodb-sync
