### ISSUE TITLE
AWS Appsync GraphQL: Resolver Request Payload does not contain "identity" in the context

### ISSUE THREAD

**Issue by tammha** [aws/aws-appsync-community#230]
Hi,
I have 2 AppSync GraphQL APIs, where one is Auth using IAM, and the other using Cognito Pools.
Both these APIs have been setup with correct roles, etc for security, because I can query and mutate data into DynamoDB.

For clients have have used:
- Postman = AWS Signature (IAM using Temp STS AccessKey/SecretKey and Session Tokens)
- Amplify API.graphQL API to make query calls.

Both the clients successfully interacted with the AppSync API server to query and mutate. I am accessing the Gql Endpoint as shown in the App Sync Console ==> Settings. That is:

https://<my-appsync-gql-id>.appsync-api.ap-southeast-2.amazonaws.com/graphql

However, in the cloudwatch logs, I can see that the payload in to the RequestMapping, there is no "identity" key. According to the documentation, I should get the identity property with their respective values depending on whether the Auth was AWS_IAM or AMAZON_COGNITO_USER_POOLS (https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference.html).

Am I missing some setting such that the identity info is not passed into the RequestMapping resolver?

**Comment by onlybakam** [comment]
Hello, AppSync does not log the `identity` part of the context in the logs, as this may contain sensitive information. You may chose to log the whole context yourself. For example in JavaScript resolvers: `console.log(ctx.identity)`.
