### ISSUE TITLE
BUG: CreatedAt used in beginsWith with several parameters requires AWSDateTime input instead of a string

### ISSUE THREAD

**Issue by vincent38wargnier** [aws/aws-appsync-community#232]
Hi, I tried to reproduce the example from the [aws documentation](https://docs.amplify.aws/cli-legacy/graphql-transformer/key/#example-get-orders-by-customer-email-by-createdat) wich proposes the following solution to create a @key that sorts results by createdAt and at the same time sorting by other parameters.

```
# Get items for order by status by createdAt.
query ListInTransitItemsForOrder {
  listItems(orderId:"order1", statusCreatedAt: { beginsWith: { status: IN_TRANSIT, createdAt: "2019" }}) {
    items {
      orderId
      status
      createdAt
      name
    }
  }
}
```

When I do this in AppSync, I get the following error : 
`Validation error of type WrongType: argument 'createdAtStatusPaymentStatus.beginsWith.createdAt' with value 'StringValue{value='2019'}' is not a valid 'AWSDateTime'`

Why is it expecting a specific type in the beginsWith option, with cannot be a AWSDateTime type while the begins with expects a part of a AWSDateTime.

Thank you.

**Comment by onlybakam** [comment]
Hello, I recommend open an issue in https://github.com/aws-amplify/amplify-cli if you are still experiencing an issue, since they provided the example and provide the library that generates that code. Note however, that there may have been updates since this issue was last opened.
