### ISSUE TITLE
How to perform Suggester Auto completion in AppSync

### ISSUE THREAD

**Issue by ygag-ameer** [aws/aws-appsync-community#234]
Hi Team,
How to perform suggester query in AppSync with Amazon OpenSearch Service Resolvers. it is perfectly ok with when running search queries. but in the case of the suggester, it failed with some error. The main thing is my completion field is like `name.suggest`. so, in the `name` field I want to perform both search and suggestion. it is ok with the search query.

eg:

    {
        "version":"2017-02-28",
        "operation":"GET",
        "path":"/brand_search/_search",
        "params":{
            "headers":{},
            "queryString":{},
            "body":{
                "from":0,
                "size":50,
                "query":{
                    "term" :{
                        "name": $util.toJson($context.arguments.name)
                    }
                }
            }
        }
    }

But, when I try to perform the suggester query it failed with some error.

    {
        "version":"2017-02-28",
        "operation":"GET",
        "path":"/brand_search/_search",
        "params":{
            "headers":{},
            "queryString":{},
            "body":{
                "from":0,
                "size":50,
                "query":{
                    "suggest": {
                      "autocomplete": {
                        "prefix": $util.toJson($context.arguments.name),
                        "completion": {
                          "field": "name.suggest"
                        }
                      }
                    }
                }
            }
        }
    }

So, here I am looking for some examples related to implementing suggesters and highlighting in AppSync with OpenSearch.

**Comment by onlybakam** [comment]
Hello, this is going to be specific to your OpenSearch. I recommend looking up the OpenSearch documentation and examples on how to interact with OpenSearch to implement this use case. You can find some info here:

- https://docs.aws.amazon.com/appsync/latest/devguide/resolver-reference-elasticsearch-js.html
- https://opensearch.org/docs/latest/query-dsl/full-text/index/
