### ISSUE TITLE
Mutations not replacing previous values

### ISSUE THREAD

**Issue by EphraimJZimmerman** [aws/aws-appsync-community#237]
I am trying to mutate a table with Python, but for whatever reason the mutation does not replace previous values, but it does create rows, and append to arrays.  I am receiving no errors, and Amplify does not provide any additional feedback about this. Is there something I should be doing differently? Across other forums this seems to be a very common issue. 

```
app_sync = AppSync(init_params)

        mutation = """mutation UpdateTable($input: UpdateTableInput!) {
        updateTable(input: $input) {
        id
        test
        }
        }
        """
        input_params = {
            "id": savedID,
            "test": "false"
        }

        response = app_sync.graphql_operation(mutation, input_params)
```

**Comment by onlybakam** [comment]
Hello, this is going to depend on the implementation of your business logic that actually implements the the update. I recommend opening a support case with AWS support if you belieave there is an issue with your AppSync API.
