### ISSUE TITLE
Recruiting spam from Amazon

### ISSUE THREAD

**Issue by jamesonwilliams** [aws/aws-appsync-community#249]
Hey there,

I'm still getting recruiting spam from Amazon.

Is this the correct place to report that?

John, Amit, Richard, Michael? You've been so helpful in the past I'm just sure you can help here. (This is a joke. You're all truly terrible.)

As I've communicated many times over email and LinkedIn, I don't want to come back to Amazon. It wasn't a good place to work.

Thanks,
Jameson

**Comment by jpignata** [comment]
No, this isn’t the correct place to report this. Send me an email and I’ll do my best to help you.
