### ISSUE TITLE
Question: availability of AppSync in South America

### ISSUE THREAD

**Issue by MathiasBerwig** [aws/aws-appsync-community#25]
I would like to know if there are any plans/schedules on offering AppSync service in other regions, especially in South America. According to [this table](https://aws.amazon.com/pt/about-aws/global-infrastructure/regional-product-services/), all major services used by AppSync (Amazon DynamoDB, Amazon Elasticsearch Service, and AWS Lambda) are already available in São Paulo.

**Comment by tinnou** [comment]
Thank you for the request. We do not share roadmap plans but I'll make sure the team sees this.

**Comment by jpignata** [comment]
AppSync is available in Sao Paolo. Thanks!
