### ISSUE TITLE
GraphQL endpoint returns 400 on mobile only

### ISSUE THREAD

**Issue by Bitkas** [aws/aws-appsync-community#252]
After hosting my application on Amplify, the graphQL endpoint return 400 - "Invalid URI Format" on mobile browsers.

![error_graphql_endpoint](https://user-images.githubusercontent.com/61255210/200124817-c04cf2f7-f32d-4a4a-9d2f-e5d5b68c116e.jpg)

The GraphQL endpoint I'm using is the one generated by amplify and matches the one shown on the amplify settings.

I tried to update the API Key but the error persists and can't find anything on the internet.

P.S: This is my first issue ever so anything I can do to improve the question just ask

**Comment by onlybakam** [comment]
Missing information about the URL used. If you are still experiencing this problem, please open a new issue. In addition, consider opening an issue on Amplify.
