### ISSUE TITLE
[Feature Request] Provide the HTTP body in the ctx.request object

### ISSUE THREAD

**Issue by bappsy3** [aws/aws-appsync-community#255]
Hello,

It would be nice to have the HTTP body available in addition to headers & domainName. That way we could proxy GraphQL requests to other AppSync services with one resolver function instead of having to have a separate resolver for every operation in the schema.

**Comment by onlybakam** [comment]
does the `info` object provide the information you are looking for:
https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference-js.html
https://aws.amazon.com/blogs/mobile/appsync-and-the-graphql-info-object/

if not, can you provide some details on the type of information you are looking for in the HTTP body?
