### ISSUE TITLE
Efficient access to DynamoDB by owner field

### ISSUE THREAD

**Issue by anatomybook** [aws/aws-appsync-community#260]
Hello,

a question came up when I looked at my scheme and its corresponding DynamoDB setup. All my tables are authenticated as follows:
```
type Search @model @auth(rules: [{ allow: owner }])
{
  id: ID!
  .
  .
  .
  .
  .
  .
}
```
This is implemented by adding an owner field on the DynamoDB side. When syncing, only items visible by the owner are accessed. DynamoDB can only rapidly access data via queries, i.e. by pk & sk or by global secondary index. What puzzles me is that the `owner` field is neither. Monitoring via CloudTrail I discovered `scan' operations on the DynamoDB tables. To me that's every inefficient.
What am I doing wrong? Is this intended this way?

As an Amplify.DataStore user, [I've posted this question already over there](https://github.com/aws-amplify/amplify-swift/issues/2675). However, they said it's an implementational detail of AppSync. Can you please shed some light on this?

Thank you very much!

**Comment by onlybakam** [comment]
closing. reference: https://github.com/aws-amplify/amplify-swift/issues/2675
