### ISSUE TITLE
RDS data source documentation for JS resolvers missing

### ISSUE THREAD

**Issue by sashee** [aws/aws-appsync-community#263]
The documentation page for RDS data sources for the Javascript runtime is missing. It is working fine, but I have to look at the VTL documentation instead.

The data source documentation list for JS resolvers:

![image](https://user-images.githubusercontent.com/82075/219857361-c48b0085-95b0-4654-baf9-91b2ccecc199.png)

And for VTL:

![image](https://user-images.githubusercontent.com/82075/219857395-f511df04-3b50-472a-8be0-c1afb23d8110.png)

**Comment by onlybakam** [comment]
duplicate. closing in favor of #264
