### ISSUE TITLE
extensions.invalidateSubscriptions function missing for JS resolvers

### ISSUE THREAD

**Issue by sashee** [aws/aws-appsync-community#265]
In VTL, there is an extensions.invalidateSubscriptions function for invalidating subscriptions:

![image](https://user-images.githubusercontent.com/82075/219857742-19165bc3-6ada-4723-808d-da720c8123ff.png)

But this is not available for JS resolvers:

![image](https://user-images.githubusercontent.com/82075/219857758-9d58518c-a596-40d2-8bad-3b2451db0d5e.png)

Without this, we need to use VTL resolvers to close subscriptions.

**Comment by lijithwv** [comment]
Similar problem here, not able to use `$extensions.setSubscriptionFilter` in a direct lambda resolver. I can implement the filtering using a VTL mapping-template. But would be nice if we can use the extensions in all resolvers.

**Comment by onlybakam** [comment]
this should be fixed. i recommend using `util.transform` as well. example in TypeScript:

```typescript
import { util } from '@aws-appsync/utils'

type Notice = { team: string; severity: number }

export function request() {}

export function response(ctx) {
  const filter = util.transform.toSubscriptionFilter<Notice>({
    team: { eq: 'mine' },
    severity: { gt: 34 },
  })
  extensions.setSubscriptionFilter(filter)
}
```
