### ISSUE TITLE
Default Arguments Not Working

### ISSUE THREAD

**Issue by princewill-ixis** [aws/aws-appsync-community#271]
Default Values not persisting in AppSync. For example via the console, when i define a simple schema like this 
`type Query {
  timeseries(
    metricName: String!
    startDate: AWSDate!
    endDate: AWSDate!
    horizon: String!
    tenant: String!
    projected: Boolean = false
    cumulative: Boolean = false
    imputed: Boolean = false
    aggregationType: String = "sum"
    aggregationLevel: String = "base"
    dateOffset: String = null
  ): [String!]!
}`

It saves, but once i refresh the page, all the default values dissapear

**Comment by onlybakam** [comment]
Hello, this is currently not supported in the console but we will look into this as a feature request.
