### ISSUE TITLE
Unexpected behavior of DynamoDB projection expression feature

### ISSUE THREAD

**Issue by sstaradubet** [aws/aws-appsync-community#274]
Hey

I have faced with unexpected behavior of [DynamoDB projection feature](https://aws.amazon.com/blogs/mobile/aws-appsync-now-supports-projection-expressions-in-dynamodb-resolvers/).

Request template

```
{
    "version" : "2018-05-29",
    "operation" : "GetItem",
    "key" : {
        "PartitionKey" : { "S" : "PartitionKey" },
        "SortKey" : { "S" : "SortKey" }
    },
    "projection": {
        "expression": "PartitionKey, SortKey, CreatedDate, UpdatedDate, Name, AttributesMap.Attribute1, AttributesMap.Attribute2"
    },
    "consistentRead" : false
}
```

In the case of **AttributesMap.Attribute2** not exists for the requested DynamoDB item request returns a null item from DynamoDB. Expected behavior, DynamoDB will return an item with all existing attributes from the projection expression and skip absent attributes (it works in this way in Python and Java SDK).

Thanks in advance!

**Comment by harish1454** [comment]
Hello, thanks for reaching out to us.

I have tried to reproduce the issue, but I see that DynamoDB returning the response by skipping the absent attributes in projection expression to AppSync, which is expected. I verified this by [enabling ALL logs](https://docs.aws.amazon.com/appsync/latest/devguide/monitoring.html#cwl) on your API and inspecting the `result` field in `ResponseMapping` log event for that request, you can also do the same.

If you still need help, please share your schema, request and response mapping template and a sample item from the DynamoDB table. Thanks!
