### ISSUE TITLE
Can't import runtime

### ISSUE THREAD

**Issue by dota-coach** [aws/aws-appsync-community#282]
AWS AppSync doesn't know runtime and does not allow me to import it. Any idea how to fix that?

![image](https://user-images.githubusercontent.com/101644718/230915507-624432e5-9065-4566-a706-89094f0913f8.png)

**Comment by onlybakam** [comment]
The console is currently not recognizing it, but saving your code will still work (to be fixed). Have you tried saving your resolver or function?

**Comment by dota-coach** [comment]
After fixing the other issues in the code it actually saved and worked :)

Thanks!
