### ISSUE TITLE
Errors when creating mergedAPI - Where to find logs

### ISSUE THREAD

**Issue by mikel67** [aws/aws-appsync-community#296]
When creating a mergedAPI with source APIs in the same account, getting the following error in the console

Error Merging API
ProductManagement-AdminAPI failed to associate with AdminUI BFF API. Error: Internal Failure while processing the merge request.

I am not finding any logs in either Cloudwatch nor Cloudtrail that provide details of the failure. Where can I get more details of this failure?

I have created a 'dummy api' manually from the console and pasted in the schema for ProductManagement-AdminAPI without creating resolvers and functions. This new API is created and merged successfully as a sourceAPI when creating the mergedAPI.

Without access to logs, doing a incremental deployment of each resolver one at a time across the API with 37 mutations and x queries to even find where the issue is to hone in will be highly tedious and time consuming.

**Comment by ndejaco2** [comment]
This was an internal system failure within AppSync. The issue should be fixed. Can you retry and if the issue still occurs can you submit a support ticket?
