### ISSUE TITLE
Problem using Open ID Connect as default authorization mode

### ISSUE THREAD

**Issue by diegoTiscarenoWizeline** [aws/aws-appsync-community#30]
I ran into this issue by trying to setup Auth0 as the auth provider for an API. This can be replicated creating one of the sample APIs from the 'Getting Started' menu: 
![image](https://user-images.githubusercontent.com/43386604/59306539-16e06880-8c62-11e9-9989-075b5e9718c0.png)
![image](https://user-images.githubusercontent.com/43386604/59306589-324b7380-8c62-11e9-8e83-c252ec9a50dd.png)

It uses API key by default, so let's change it for OIDC:

![image](https://user-images.githubusercontent.com/43386604/59307085-59ef0b80-8c63-11e9-89e2-261b8dd4c2f7.png)

After this, navigating to the "Queries" section, and pasting a valid Auth0 token results in a successful query, as we might expect:

![image](https://user-images.githubusercontent.com/43386604/59307754-d2a29780-8c64-11e9-9eac-eb9262baa46e.png)

The problematic bit comes next. If I add an API key as an additional type: 

![image](https://user-images.githubusercontent.com/43386604/59307361-faddc680-8c63-11e9-985b-d8dec21ec446.png)

and I go back to the queries section, and try to execute the same query, using OIDC again, it stops working: 

![image](https://user-images.githubusercontent.com/43386604/59307546-5b6d0380-8c64-11e9-8079-13bfc2d4744b.png)

The error seems to suggest that AppSync is not being able to parse the token:
```
{
  "errors": [
    {
      "errorType": "UnauthorizedException",
      "message": "Valid authorization header not provided."
    }
  ]
}
```

If at this point, I delete the additional API key, it works again as expected.

I tried to dig a bit further into the issue, trying different combinations of auth types, and found the following:

If I add a Cognito User Pool, and query something authenticated to the Pool, AppSync will correctly tell me that I have no access to the resource, as I never gave the schema the `@aws_cognito_user_pools` directive: 

<img width="1246" alt="Screen Shot 2019-06-11 at 4 32 30 PM" src="https://user-images.githubusercontent.com/43386604/59308532-e222e000-8c66-11e9-8860-fe0c4a3eff60.png">

Notice how the response status is 200, and AppSync informs me how I'm not authorized, rather than not passing a correct header, as before. 
Going even deeper, if I copy the JWT generated by Cognito, and paste it using OIDC, This time I get the error stating I'm not authorized: 

![image](https://user-images.githubusercontent.com/43386604/59308758-73925200-8c67-11e9-9f10-0f66f313061e.png)

This is strange, because when using the correct Auth0 token, it actually fails with the message `Valid authorization header not provided.` as in not receiving the auth header at all, which would suggest to me that AppSync is treating all tokens as Cognito JWTs, even though it shouldn't, because my default is OIDC (I can see how this would be problematic for AppSycn since Cognito also uses OIDC behind the scenes).

Just in case this was something related to the AWS console, I also tried creating a JS app using the `AWSAppSyncClient`, but the result was the same.

Not sure if this is supposed to work like this when using OIDC as default, but I couldn't find anything in the documentation that suggested this was not possible.

Any suggestion would be greatly appreciated, thank you!

**Comment by itrestian** [comment]
I suspect the issuer you have configured in the OpenID Connect authorization provider in AppSync doesn't match the one in the Auth0 jwt token (Auth0 jwt tokens have a trailing slash for the issuer). Matching the issuer exactly in the configuration should solve this issue. Like you mentioned, when adding the user pool, that is the expected behavior since you have a valid provider yet no schema directives to give you access.

When we grab the different authorization provider configs, we do an exact match between the issuer you have configured on the AppSync API and the one in the JWT to know which configuration to apply.

**Comment by diegoTiscarenoWizeline** [comment]
@itrestian You are exactly right 😄 . The fact that it worked without the slash while being the default and no other modes present totally threw me off. 
Thank you very much!

**Comment by cloudspeak** [comment]
Hi @itrestian, I'm facing an almost identical situation, except that as far as I can see, my issuer is correct.  Just to check, are you saying that the issuer in the token must match the issuer given by my OIDC provider's `/.well-known/openid-configuration`?  And is there anything else which must match or which could cause this error?  We have implemented our own OIDC provider so we may have missed something.  Thanks!
