### ISSUE TITLE
@aws-appsync/eslint-plugin does allow functions returning function for arrow functions

### ISSUE THREAD

**Issue by WolfWalter** [aws/aws-appsync-community#304]
The APPSYNC_JS runtime sadly does not support returning function from functions:
https://docs.aws.amazon.com/appsync/latest/devguide/resolver-reference-overview-js.html#:~:text=cannot%20be%20reassigned.-,no%2Dfunction%2Dreturn,-Functions%20cannot%20be

The esllint rule should give an error when the `no-function-return` is active (set by @aws-appsync/recommended). That does work fine for normal functions:
```
function test() {
  return () => {
    return null;
  };
}
```
But does not trigger for arrow functions:
```
const test = () => () => {
  return null;
};
```

**Comment by onlybakam** [comment]
This issue has been fixed in the latest version of the plugin
