### ISSUE TITLE
Use AWS amplify with AWS APPSync GraphQL API where aws_appsync_authenticationType is OPENID_CONNECT

### ISSUE THREAD

**Issue by khaleeq-nicoin** [aws/aws-appsync-community#309]
Hi,

I have AWS APPSync GraphQL API with lambda resolvers and ws_appsync_authenticationType is OPENID_CONNECT. I want to use AWS amplify with this api. OPENID_CONNECT is the only authentication method which i have to use with amplify and appsync. 

I followed the appsync "Integrate with your app" guide 
npm install -g @aws-amplify/cli
amplify init
amplify add codegen --apiId .....
amplify codegen

it created an amplify project and added/generated the appsync api queries, mutations etc.

i configured amplify project following "use existing resource" and standard approach.

but i am getting AuthErro: amplify is not configured correctly ... when i send api using aws-amplify API module.

there is no proper documentation where it explains how we can integrate aws amplify with an existing system and solely use OPENID_CONNECT with it.

**Comment by onlybakam** [comment]
Hi, could you open an issue in the Amplify repo as this is an Amplify configuration issue?
