### ISSUE TITLE
Additional Indexes

### ISSUE THREAD

**Issue by dancomanlive** [aws/aws-appsync-community#32]
Do Additional Indexes only support Global Secondary Indexes? If so how can we add Local Secondary Indexes?

<img width="1181" alt="Screen Shot 2019-06-17 at 00 09 44" src="https://user-images.githubusercontent.com/16872821/59566654-940e4200-9095-11e9-88e6-a262c3fe69e2.png">

**Comment by dancomanlive** [comment]
"You can also select indices for different query options, which set up a DynamoDB local secondary index or global secondary indexes, as appropriate."

https://docs.aws.amazon.com/appsync/latest/devguide/provision-from-schema.html#aws-appsync-provision-from-schema

The answer seems to be both. I assume that if the same primary key is chosen for an additional index then a local secondary index is created.

**Comment by AaronHarris** [comment]
You can add a Local Secondary Index by specifying an index with the same primary key and additional sort key, as you've done in the screenshot above. The console will intelligently determine whether to use a global or local secondary index based on the key selection. 

Keep in mind, embedding this screen is merely a shortcut to using the full Amazon DyanmoDB console, with the benefit of automatically generating the graphql and resolvers for DynamoDB. If you don't like the table that's been generated, you can always delete it and replace it with a table of the same name, and then go through and update your AppSync API as desired (with the correct IAM access roles for your data source, and desired index to query).

**Comment by dancomanlive** [comment]
@AaronHarris Thank you for the reply. It was not clear from the docs that the console will intelligently determine whether to use a global or local secondary index. I created an additional index and auto-generated the API, then looked at the Indexes tab on the table in DynamoDB and saw indeed there is a Type LSI. Initially I assumed that the Indexes tab is only for GSIs for some reason.

Apparently automatic code generation is offered in two forms. One of them can be done via the AppSync Management console and the other is done using the AWS Amplify CLI. Is there any other way of doing it, via the AWS Javascript SDK maybe? My goal is to be able to do automatic code generation programatically without using the console or Amplify.
