### ISSUE TITLE
Phasing out our doc support for VTL in favor of APPSYNC_JS?

### ISSUE THREAD

**Issue by zales2** [aws/aws-appsync-community#320]
There is a warning "We're slowly phasing out our doc support for VTL in favor of APPSYNC_JS. Please consider using the APPSYNC_JS runtime and its guides [here](https://docs.aws.amazon.com/appsync/latest/devguide/tutorials-js.html)." on: https://docs.aws.amazon.com/appsync/latest/devguide/tutorials.html. Do you have more information about it because it is quite concerning?

**Comment by onlybakam** [comment]
VTL is still supported. We do recommend to use JavaScript resolvers for an enhanced experience, but you can always use VTL and refer to the VTL docs for information about the VTL features.
