### ISSUE TITLE
Console.log doesn't seem to work in Javascript resolvers

### ISSUE THREAD

**Issue by mrForce** [aws/aws-appsync-community#321]
While on a call with AWS Support, we noticed that using console.log doesn't seem to work in JS resolvers. Has anyone else had this issue?

Resolver (simple example):
`
/**
 * Scans the DynamoDB datasource. Scans up to the provided `limit` and stards from the provided `NextToken` (optional).
 * @param {import('@aws-appsync/utils').Context} ctx the context
 * @returns {import('@aws-appsync/utils').DynamoDBScanRequest} the request
 */
export function request(ctx) {
  console.log("hello");
  return { operation: "Scan" };
}

/**
 * Returns the scanned items
 * @param {import('@aws-appsync/utils').Context} ctx the context
 * @returns {*} a flat list of results from the Scan operation
 */
export function response(ctx) {
  return ctx.result.items;
}
`

It logs an ExecutionSummary, and then a RequestSummary. But it doesn't log hello (I've tried a few different console.log in both request and response, and none of them worked).

**Comment by ATaiIsHere** [comment]
Verify that the 'Field resolver log level' in the AppSync settings is set to 'ALL'.

**Comment by thetoxicavenger** [comment]
@mrForce did that resolve your issue? I've been getting `stack failed to deploy` CDK errors when using `console.log` or `console.error` in my resolvers.

**Comment by onlybakam** [comment]
@mrForce let us know if you're still experiencing this issue.
@thetoxicavenger can you share more details or open a case with AWS Support?

**Comment by mrForce** [comment]
> Verify that the 'Field resolver log level' in the AppSync settings is set to 'ALL'.

Yes, that fixed it. I'll close the issue out now.
