### ISSUE TITLE
[Feature Request] improve log levels

### ISSUE THREAD

**Issue by chemdrew** [aws/aws-appsync-community#333]
Currently there are only 3 options for log levels: NONE, ERROR, TRACE

Tracing contains all field level stats from aws and is _very noisy_

Error logging only shows console.error logs and no console.log or info logs

It would be incredibly useful if there was an INFO level in appsync that would omit the aws tracing logs, but preserve any console.log messages

**Comment by ATaiIsHere** [comment]
Good suggestion!

**Comment by onlybakam** [comment]
We've added support for additional log levels - https://aws.amazon.com/about-aws/whats-new/2024/09/aws-appsync-api-monitoring-debug-info-logging-levels/

**Comment by chemdrew** [comment]
@onlybakam thank you!
