### ISSUE TITLE
GraphQL error: Throughput exceeds the current capacity of your table or index.

### ISSUE THREAD

**Issue by nithin-viswanathan** [aws/aws-appsync-community#336]
We are getting the below error when we fetch multiple records from dynamo db.

_Issues in fetching plan data GraphQL error: Throughput exceeds the current capacity of your table or index. 
DynamoDB is automatically scaling your table or index so please try again shortly. If exceptions persist, 
check if you have a hot key:_

`const client = new AWSAppSyncClient({
        url: aws_exports.aws_appsync_graphqlEndpoint,
        region: aws_exports.aws_appsync_region,
        auth: {
            type: AUTH_TYPE.AWS_LAMBDA,
            token: () => getFunctionToken()
        },
        disableOffline: true
    });`

What may be the reason for this? How can we solve this

**Comment by saltman424** [comment]
@nithin-viswanathan it doesn't sound like an AppSync issue. It sounds like an issue with your DynamoDB configuration. I would recommend closing this issue and looking [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TroubleshootingThrottling.html) for tips on how to debug DynamoDB throttling problems

If you continue to have issues, you should open up a StackOverflow issue and post more details there
