### ISSUE TITLE
Automatic code generation

### ISSUE THREAD

**Issue by dancomanlive** [aws/aws-appsync-community#34]
Automatic code generation is offered in two forms. One of them can be done via the AppSync Management console and the other is done using the AWS Amplify CLI. Is there any other way of doing it(via the AWS Javascript SDK maybe)? The objective is to be able to do automatic code generation programatically without using the AppSync console or Amplify.

**Comment by ashwindevendran** [comment]
Hi, as you mentioned the code-gen is currently only possible via the console or amplify cli. I would recommend you create an issue in the AmplifyJS SDK github repo for introducing code-gen functionality (as they make essentially make it easier to interact with AWS services on top of the AWS JS SDK). 

Repo here: https://github.com/aws-amplify/amplify-js

**Comment by buggy** [comment]
You can use the Amplify transformers without Amplify. I've used it to generate a SAM application.

**Comment by jpignata** [comment]
Closing in favor of a CLI issue.
