### ISSUE TITLE
[JS] Comparison of numbers from dynamodb response is wrong

### ISSUE THREAD

**Issue by LucasVera** [aws/aws-appsync-community#344]
## Issue
Hi There! Currently ran into an issue when trying to compare two numbers in an appsync js resolver. Both these numbers come from two number fields from dynamodb, and after doing a `GetItem` operation in the request, I try to compare them in the response, however the logic seems to be reversed (also happened to me with a `query` operation, however didn't take evidence of that)

#### Dynamodb data
This is the dynamodb data being fetched:
![image](https://github.com/aws/aws-appsync-community/assets/20703632/b9d64cca-c8b2-4994-ae8b-ee5744922757)
```
{
 "id": "1",
 "num1": 40,
 "num2": 40
}
```

#### Resolver code
The resolver code is the following:
```
import { util } from '@aws-appsync/utils';
export function request (ctx) {
  return { operation: 'GetItem', key: util.dynamodb.toMapValues({ id: "1" })};
}

export function response (ctx) {
  const { result } = ctx;
  
  console.log('dynamodb result:', result)

  const num1 = result.num1; // 40 in dynamodb
  const num2 = result.num2; // 40 in dynamodb

  console.log('num1 value', num1)
  console.log('num1 type', typeof num1)
  console.log('num2 value', num2)
  console.log('num2 type', typeof num2)
  console.log('this should be true -->', num1 === num2);
  console.log('this should be false -->', num1 !== num2);

  return {};
}
```

#### Cloudwatch logs
After executing, the results in cloudwatch are the following:
![image](https://github.com/aws/aws-appsync-community/assets/20703632/a8fa01eb-68d9-476f-8d44-cec85da5a4cd)

Notice that the logs show the value of `num1` and `num2` to be `40`, and the types are both `number`, however the comparison logs are reversed.

## Workaround
Curiously enough, after adding a ` + 0` to `num1` and `num2`, the comparisons would start working again:

#### Updated resolver code with the workaround
```
import { util } from '@aws-appsync/utils';
export function request (ctx) {
  return { operation: 'GetItem', key: util.dynamodb.toMapValues({ id: "1" })};
}

export function response (ctx) {
  const { result } = ctx;
  
  console.log('dynamodb result:', result)

  const num1 = result.num1 + 0; // 40 in dynamodb
  const num2 = result.num2 + 0; // 40 in dynamodb

  console.log('num1 value', num1)
  console.log('num1 type', typeof num1)
  console.log('num2 value', num2)
  console.log('num2 type', typeof num2)
  console.log('this should be true -->', num1 === num2);
  console.log('this should be false -->', num1 !== num2);

  return {};
}

```

#### Cloudwatch logs with workaround
![image](https://github.com/aws/aws-appsync-community/assets/20703632/e60748c4-0ea0-435f-9d64-18fbda1bda5f)

**Comment by gilbertw1** [comment]
Thanks for the detailed report. We'll look into this.

**Comment by gilbertw1** [comment]
This issue has been resolved, please let us know if you run into any further problems.
