### ISSUE TITLE
I believe it is not possible to create the graphql schema dynamically, so the alternative solution would be to create VTL programmatically with CDK java

### ISSUE THREAD

**Issue by LucianViana** [aws/aws-appsync-community#357]
Is there already the creation of the VTL programmatically by CDK as it says in the video:
https://www.youtube.com/live/I-L89SpoDxI?si=obBr24LE9b73vud7

**Comment by onlybakam** [comment]
Hi, please take a look at https://docs.amplify.aws/gen2/build-a-backend/data/set-up-data/ to do some of this automatically. 

I also recommend looking at AppSync JS resolvers: https://docs.aws.amazon.com/appsync/latest/devguide/resolver-reference-overview-js.html
