### ISSUE TITLE
Can appsync update subscriptions for multiple cognito logins

### ISSUE THREAD

**Issue by balkat** [aws/aws-appsync-community#4]
Our app design requires that multiple cognito IDs be logged in at the same time.
I want to check that any subscription notifications for any of the IDs would be pushed.
AFAICT this would mean that the appsync layer would need to keep multiple websocket connections open.

Is this supported by appsync?

**Comment by itrestian** [comment]
AWS AppSync yes. You might want to check on the forum corresponding to the particular SDK you are using to see if/how multiple logged in users are supported.
