### ISSUE TITLE
Bug: AppSync console renders schema with syntax errors

### ISSUE THREAD

**Issue by timo92** [aws/aws-appsync-community#41]
### Issue
When entering a schema definition which includes directives in AppSync console or creating it via cloudformation the schema will be rendered with syntax error in AppSync console. Queries and Mutations still work but the schema can't be modified in the console.
I've been noticing this issue since July 31.

### Example
```
type Example implements ExampleInt @aws_api_key {
	name: String
	description: String
}

interface ExampleInt {
	name: String
}

type Query {
	getExample: [Example!]!
}
```

will be rendered as 
```
type Example @aws_api_key implements ExampleInt {
	name: String
	description: String
}

interface ExampleInt {
	name: String
}

type Query {
	getExample: [Example!]!
}
```

Any modification to this schema definition will yield
```
Syntax Error GraphQL request (1:27) Expected {, found Name "implements"
```

**Comment by tinnou** [comment]
Thank you for the report, I was able to reproduce as well and we will get this fixed.

**Comment by timo92** [comment]
This Issue is no longer reproducible, I'm assuming it has been fixed.
