### ISSUE TITLE
Make the current type and field available in the context

### ISSUE THREAD

**Issue by buggy** [aws/aws-appsync-community#45]
Could you make the name of the type and field being accessed available in context for the resolver?

For example: If my schema was

```graphql
type User {
  name: String
}

type Query {
  me: User
}
```

The `Query.me` resolver would have `Query` as the type and `me` as the field in the context. In the `User.name` resolver it would have `User` as the type and `name` as the field.

I have a function in a pipeline resolver that needs to know which type and field it is being invoked for. Currently I have the value hard coded into the before mapping template in the pipeline which sets it in the stash allowing functions to find it.

**Comment by jbailey2010** [comment]
Hi,

Thanks for the feedback! This is a totally reasonable request, and I'll bring it back to the team for prioritization.

**Comment by tinnou** [comment]
We listened! We just released the `$ctx.info` object. You can now access the parent type and the current field name by using `$ctx.info.parentTypeName` and `$ctx.info.fieldName` respectively. More info here https://aws.amazon.com/blogs/mobile/appsync-and-the-graphql-info-object/

**Comment by tinnou** [comment]
Feature has been released 823d9c6 , closing.
