### ISSUE TITLE
Feature Request: a way to evaluate VTL templates locally

### ISSUE THREAD

**Issue by erezrokah** [aws/aws-appsync-community#46]
Ideally I would like to be able to do something like this in a Unit Test:

```
expect(evaulateVTL(context, template)).toEqual(expectedTemplate);
```

I found this [unofficial tool](https://github.com/ToQoz/api-gateway-mapping-template) for API Gateway mapping (it is outdated but works).

The AppSync console already has this functionally and even provides useful context sample objects.

Correct me if I'm wrong but [this](https://aws.amazon.com/blogs/mobile/amplify-framework-local-mocking/) will only check the template for errors.

**Comment by undefobj** [comment]
Hi we recently released mocking support in the GraphQL Transformer for Amplify: https://aws-amplify.github.io/docs/cli-toolchain/usage#graphql-resolver-debugging

**Comment by bjacobel** [comment]
Just adding the API at `https://[region].console.aws.amazon.com/appsync/extension/evaluateMappingTemplate` to the publicly supported API so we could hit it from API clients (cli, js-sdk) would be very helpful.

**Comment by AaronHarris** [comment]
Closing this issue, as we have released this feature.

**Comment by erezrokah** [comment]
Hi @AaronHarris, can you share a link to the docs with this release?

**Comment by p0wl** [comment]
Is the `https://[region].console.aws.amazon.com/appsync/extension/evaluateMappingTemplate` endpoint real? how to use it?
