### ISSUE TITLE
[Question] Is there any Vtl support for date manipulation?

### ISSUE THREAD

**Issue by Sunac** [aws/aws-appsync-community#47]
I'm struggling with my AppSync request resolver, actually VTL when it comes to performing several operation on passed AWSDateTime arguments, like subtracting or adding day, time etc. depending on business requirement.
Only parsing/formating current date/time is supported using helpers, but I need to add day or month to the current date or date arguments and perform DynamoDB query based on that range. 
Am I missing something, or this is not possible. If it's N/A then it should be added. Thanks!

**Comment by Sunac** [comment]
The question should be closed since it's redundant. 
Of course, it would be great to have support for $util.date manipulation but for this purpose I've asked, existing time utils can be used - manipulation can be done using existing epoch time utils and then convert it back to ISO8601 using existing time helper which accepts long value and returns formatted one further needed. Like this for example:
`#set( $currentTimeEpoch = $util.time.nowEpochMilliSeconds())
#set( $fromStartEpoch = $currentTimeEpoch + (1000 * 60 * 60 * 24))
#set( $currentTime = $util.time.epochMilliSecondsToISO8601($currentTimeEpoch))
#set( $fromStart = $util.time.epochMilliSecondsToISO8601($fromStartEpoch))`

**Comment by ReemaDass** [comment]
hey i am writing a resolver in which i need to check dates but my field in dynamo table had datetime.. i need to format this datetime to date and do my comparision..
can anyone help me with how this can be achieved
