### ISSUE TITLE
Feature Request: Make requested fields accessible in resolver mapping template context

### ISSUE THREAD

**Issue by s3ru** [aws/aws-appsync-community#49]
Having access to the requested fields in the resolver [$context](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference.html) object would allow use to write more optimized database queries: 

- Avoiding expensive/unnecessary Joins in RDS
- Utilizing DynamoDB's projection-expressions (dropping out large columns)

Currently the requested fields are not exposed in `$context.arguments` or `$context.request`.
This feature would be very helpful for our team.

**Comment by jbailey2010** [comment]
Thanks for the feedback! I'll note this as a feature request and take it back to the team for prioritization.

**Comment by SkylarWapato** [comment]
Any movement on this, or a tentative timeline?

**Comment by tinnou** [comment]
We just released the `$ctx.info`object now available in all resolvers. For example to retrieve the current selection set at the current field you can use `$ctx.info.selectionSetList`.  More details here https://aws.amazon.com/about-aws/whats-new/2020/02/aws-appsync-releases-integration-with-aws-x-ray-and-graphql-info-object-support/

**Comment by tinnou** [comment]
Feature has been released 823d9c6 , closing.
