### ISSUE TITLE
Feature Request: Custom domain names

### ISSUE THREAD

**Issue by buggy** [aws/aws-appsync-community#5]
Currently AppSync generates a random API endpoint. If the endpoint is ever deleted (accidentally or otherwise) then you cannot re-create an API with the old API endpoint which breaks existing clients. If we can assign a custom domain name, like `api.example.com`, to an AppSync instance then we could move the name from the old instance to the new one and keep clients working.

**Comment by AaronHarris** [comment]
Thank you for the request. At this time, you can have a Route53 record that points to your AppSync endpoint, which you can update if your endpoint ever changes. However, this won't work if you're using IAM for authentication. Take a look at this blog post which details it further: https://aws.amazon.com/blogs/mobile/use-a-custom-domain-with-aws-appsync-amazon-cloudfront-and-amazon-route-53/

**Comment by dale-jepto** [comment]
I tried setting this up but couldn't get it working and got the following error: 

> This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests.

Can you confirm the cache settings that need to be used.

**Comment by shduke** [comment]
API Gateway on CloudFront [supports IAM authorization](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html) for custom domain aliased endpoints. Is there any plans to add this support for AppSync endpoints? See this [post](https://stackoverflow.com/questions/48815143/does-api-gateway-behind-cloudfront-not-support-aws-iam-authentication?rq=1) regarding this same issue for APIG.

**Comment by meije702** [comment]
It amazes me that after a year there is no real world solution for this. Even if we have all the components within the AWS walled garden the current solution is finicky at best, any response on the status of this "enhancement" would be greatly appreciated thank you.

**Comment by BryanCrotaz** [comment]
> At this time, you can have a Route53 record that points to your AppSync endpoint, which you can update if your endpoint ever changes

Where do you set the AppSync cert to support SSL on the Route53 domain name?

**Comment by tezqa** [comment]
@bri

> > At this time, you can have a Route53 record that points to your AppSync endpoint, which you can update if your endpoint ever changes
> 
> Where do you set the AppSync cert to support SSL on the Route53 domain name?

You can’t. You have to use CloudFront for that. Everything is explained in this post:
https://aws.amazon.com/blogs/mobile/use-a-custom-domain-with-aws-appsync-amazon-cloudfront-and-amazon-route-53/

**Comment by jacques-** [comment]
If you are not deploying appsync in N.Virginia region you need to deploy multiple stacks in multiple regions to get this working. Seems like so much overhead when you are using none of the cahcing or any other features of CF. 

Would be awesome if appsync allowed custom domain like api gateway does.

**Comment by alextriaca** [comment]
Please can this feature request get some love. This is quite an important feature to allow clean use of Appsync. Without this feature most discussions end up circling back round to just using API Gateway.

**Comment by tyroneerasmus** [comment]
Agree with comments above, this feels like something that could help Appsync feel more ready for prime time. Sure, there are some sticky tape solutions that can be done, but nothing will beat being able to configure a custom domain natively in Appsync.

**Comment by BryanCrotaz** [comment]
This should also allow support of GraphQL subscriptions which would be a nice benefit

**Comment by p0wl** [comment]
Any update on this? Is there any place where we can vote for this feature?

**Comment by BennettSmith** [comment]
Having the ability to map a custom domain and endpoint (ex. https://api.mycompany.com/v1/) to a specific AppSync deployment would go a long way to making AppSync a stable tool to use over time. 

As it is, I am very nervous about shipping native clients that rely on AppSync. It seems very fragile in its current form.

**Comment by bboure** [comment]
I would like to support this feature request. It is primordial to be have a good solution to support custom domain. 
We are building a mobile app and as we are approaching the beta launch date, I am starting to feel a bit nervous about this.
As stated in the original request, if for any reason, the endpoint gets deleted, all clients will stop working. This is a real problem, especially for mobile where we do not have control on the client version installed on each device.

Thanks

**Comment by paulsson** [comment]
@awsed @dabit3 any way you guys can help get some traction for supporting AppSync custom domain names when using IAM for request authentication? This issue has been around for 1.5 years with everyone asking custom domain support when using IAM auth.
I feel AppSync isn't being promoted to its full potential... All the AWS marketing and docs really only focus on using it for mobile or web apps but I would also promote it as a way to build standalone APIs as well. When  using AppSync as a GraphQL API that other systems can use (systems running within AWS) then those systems should be using IAM for the AppSync auth and they should be using a Route53 defined domain name so that a change that affects the AppSync domain/URL doesn't also trickle down to a config change for every other system that is a client of the AppSync API.

I would imagine this would work pretty much the same way that "custom domain names" work for API Gateway.
Thoughts?

Thanks!
Erik

**Comment by zevmo** [comment]
I'd like to reiterate, after yesterday's us-east-1 issue, how important it is to have a solution for this. Mobile apps **cannot** be locked to a single AWS region.

**Comment by ivands** [comment]
Can someone from the AWS team please respond to this.
We are running app sync at scale and are paying extra CloudFront costs for no other reason than to have our own custom domain.
I find this ridiculous.
Amazon always has some weird workaround for basic functionality that will cost you a lot of unexpected / unneeded money in the long run.

**Comment by guillesha** [comment]
Hi, 

I am needing this feature also. The ability to manage custom domain names like in API Gateway is much needed to specify minimum  TLS version. 

Thanks

**Comment by jonathanarevalogaray** [comment]
We need this feature too.

**Comment by sebastian-wirkert** [comment]
Hey, we are very interested as well

**Comment by DougFigueroa** [comment]
We really need this feature too.

**Comment by drewler9** [comment]
We also need this feature, for appsync to really shine. 
Being able to manage appsync services for others to use, requires us to control custom domain name across deployments, and to make a better experience around.

**Comment by SergiuTalnaci** [comment]
Hey, please add custom domain, this feature is a must have.

**Comment by DanielLaberge** [comment]
It feels contrived and wrong to put CloudFront in front of AppSync for the sole purpose of accepting traffic with HTTPS and a custom domain name. Please provide a better (native) solution.

**Comment by plgingras88** [comment]
This really needs to be addressed asap, please !

**Comment by themetis** [comment]
Please we need this feature!

**Comment by paulnolan7** [comment]
We need this feature as well, with both IAM auth support and subscriptions

**Comment by Dachmian** [comment]
We need this feature too

**Comment by mirstan** [comment]
The current workaround doesn't work for us because of subscriptions.

**Comment by matomer** [comment]
This behavior presents a security issue if custom authorization is used with cloudfront (as described [https://aws.amazon.com/blogs/mobile/appsync-custom-auth/](here)). Even if you put custom authorization on the cloudfront distribution, a malicious actor can theoretically find your public graphql endpoint and use it to get around the custom authorization. As long as there's no way to at least disable the custom endpoint, I don't see how you can say that appsync graphql supports custom authorization.

**Comment by ivands** [comment]
Ok soooo because i have to put a Cloudfront in front of our AppSync API, I can't use the user-agent & ip-country headers anymore. Please AWS give us native custom domains already.

**Comment by bboure** [comment]
@ivands Yo should be able to forwards the headers through Origin request policies

**Comment by ivands** [comment]
> @ivands Yo should be able to forwards the headers through Origin request policies
Oh thank you. I wil try that.

**Comment by acossta** [comment]
we need this too. Any update?

**Comment by awsed** [comment]
Thank you for the interest, this is something we plan to release in the future however we don't have an ETA to share for now. Stay tuned!

**Comment by nagababu04** [comment]
we need this too. Any update?

**Comment by danielblignaut** [comment]
we need this too

**Comment by omkardeshpande3194** [comment]
We need this too, any update on this? Please share if you are planning this feature or not. Any estimated dates would be great.

**Comment by onlybakam** [comment]
Hey all, thanks again for the interest in this feature. I'm looking into this a bit more closely. Would really appreciate if you could answer these 2 questions:

* What is your primary requirement for using custom domains with AppSync?
* What are the top 3 functionalities you must get from a custom domains feature?

**Comment by denniscmpe** [comment]
With a custom domain we can perform DNS failover in Route53 with multi-region AppSync deployments.

Currently, we do this by placing API Gateway (which provides custom domains) in front of AppSync.

**Comment by joebernard** [comment]
Primary requirement: Stability. We have no control over our production AppSync endpoint. If it changed we'd be stuck rolling out an emergency update to all our mobile apps. It would be preferable to allow customers to control their own endpoint domains in DNS, which then point to the AppSync domain. If the AppSync endpoint domain ever changes we can quickly mitigate the problem in DNS.

Right now it is a massive single-point-of-failure potential.

**Comment by rozzs74** [comment]
The custom domain name is not supporting the web socket network connection that is utilising by GraphQL subscription.

I would like to make a feature request to support this on web socket URL

**Comment by skwashd** [comment]
Primary motivation: user friendly URLs

Top functionality:
1. IAM auth - AppSync is a major component in our internal automation platform where all clients use IAM roles for auth
2. Not losing the domain if someone really messes up the cfn template
3. I think that's it

**Comment by onlybakam** [comment]
> Primary requirement: Stability. We have no control over our production AppSync endpoint. If it changed we'd be stuck rolling out an emergency update to all our mobile apps. It would be preferable to allow customers to control their own endpoint domains in DNS, which then point to the AppSync domain. If the AppSync endpoint domain ever changes we can quickly mitigate the problem in DNS.


@joebernard if you could auto-magically connect to the default real-time endpoint for subscriptions just by knowing your custom domain AppSync endpoint, would this meet your stability needs?

**Comment by joebernard** [comment]
@onlybakam Yes, though to be clear we would need this to apply to all appsync connections, not just subscriptions. I think that's what you meant but just wanted to be sure. If we can own the domains we use for appsync endpoints that would satisfy our requirements.

**Comment by dominixdesign** [comment]
> * What is your primary requirement for using custom domains with AppSync?

We have a IoT setup with appsync running. So, if the URL changes (new stack, downtimes, etc.) after the IoT device is at the customer the customer needs to update his devices manually to get a new URL. Yes that should not happen that often, but if something is broken, we brick some devices without a chance to fix them remotely.
If we have a custom URL, it will only have some hiccups, but will working again without any actions by the customer.

> * What are the top 3 functionalities you must get from a custom domains feature?

1. full appsync feature set. so subscriptions/websockets as well
2. DNS management on our side (we own the domain and can use any DNS)
3. available as soon as possible 🙈

Thanks for your time 🙌

**Comment by soplan** [comment]
> Hey all, thanks again for the interest in this feature. I'm looking into this a bit more closely. Would really appreciate if you could answer these 2 questions:
> 
> * What is your primary requirement for using custom domains with AppSync?
> * What are the top 3 functionalities you must get from a custom domains feature?

We need it to be able to provide a FQDN to our clients which have strict firewall rules in place. They will not accept *amazon.com addresses.
We need it to only allow strong ciphers and TLS 1.2 and 1.3 (we need to disable tls 1.1 and weak ciphers. Currently we score B on ssllabs.com

**Comment by bboure** [comment]
https://aws.amazon.com/blogs/mobile/introducing-custom-domain-names-for-aws-appsync-apis/

🎉

**Comment by zevmo** [comment]
I saw this... SO HAPPY!

Thank you!
_________________________________
*Zev Mo Green*
Principal Product Manager - Fintech Product Owner - GSD - Technologist
*                 IDT Corporation                   *
           *BOSS Revolution Money          *
Set a meeting: https://calendly.com/zevmo
e: ***@***.*** | m: 201-905-0305

*"The way to get started is to quit talking and begin doing."*
- Walt Disney
*CONFIDENTIALITY NOTICE: **The contents of this message, together with any
attachments, are intended only for the use of the person(s) to which they
are addressed and may contain confidential and/or privileged information.  **If
you are not the intended recipient, immediately advise the sender and
delete this message and any attachments. The contents of this email may
contain *IDT Proprietary & Confidential Information.



* Any distribution, or copying of this message, or any attachment, is
prohibited.*

**Comment by zevmo** [comment]
So happy! Wonderful news. Thank you.

**Comment by awsed** [comment]
Happy to report this is indeed now supported in AppSync: 

https://aws.amazon.com/about-aws/whats-new/2021/12/aws-appsync-supports-custom-domain-names-appsync-graphql-endpoints/

Thank you all for the patience and feedback!

**Comment by soplan** [comment]
Has someone tested it? 

We are testing it today and it seems that the graphql endpoint on the custom domain is not working.

Trying to see if someone else experience same problem or is it just me.
