### ISSUE TITLE
Feature Request: Public access to AppSync behind CloudFront

### ISSUE THREAD

**Issue by Dlozitskiy** [aws/aws-appsync-community#50]
Hello,

We have an architecture where two AppSync instances are configured as origins behind CloudFront distribution and one of the origins is assigned to default cache behaviour at a time. This is to enable Blue/Green type of deployment to static backend datasources. AppSync Authentication is set to AWS Cognito.

Everything works fine, until recently where we got a requirement to enable public access to some of the queries on AppSync - the is where we are facing issues with current AppSync limitations.

a) We can't use AWS IAM with Cogntio Identity Pools Identities because it doesn't work with custom domain names, the request should come to AppSync API directly instead of CloudFront for this to work (https://aws.amazon.com/blogs/mobile/use-a-custom-domain-with-aws-appsync-amazon-cloudfront-and-amazon-route-53/):

```
**Restrictions**

You can configure a custom domain for AWS AppSync for all authentication methods except AWS_IAM.  Configure a custom domain for any of the other authentication mechanisms–OpenID Connect, Amazon Cognito user pools and an API key.
```

b) We can't use AppSync API Keys either as they are different on two AppSync instances behind CloudFront, and client app will be confused not knowing which key to use at which point of time.

I understand that "a" can't be implemented due to how AWS Signature works, however if we have a control over API Key that is provisioned in AppSync that would solve the issue.

So if there are no alternative solutions to our problem our feature request will be: Allow importing/sharing API Keys between multiple AppSync instances.

**Comment by katzeforest** [comment]
I will forward to the team about this feature request. Thank you!

**Comment by undefobj** [comment]
@Dlozitskiy one option today is you might use Lamda@Edge to control what API Key is sent to your origin, which would allow you to use Multi Auth in AppSync and have your Public access be API Key. Then in your Lambda@Edge function check the value of the key and change it appropriately. Could be a simple If/Else statement to only change one value since you're in a Blue/Green setup.

**Comment by Dlozitskiy** [comment]
Thanks for a comment @undefobj 

I chose similar approach but using  `client_credentials` grant to fetch Cogntio access token from Lambda and add it as a Authorization header to current AppSync origin.

I'll post a snippet of the code here later and close the request.

**Comment by Dlozitskiy** [comment]
Below is a working example:

Cache behavior on CloudFront distribution is based on the /public path pattern and routes the request to the same graphql origin.

The behaviour has a Lambda @ Edge function attached to it to modify request to origin by requesting an access token from Cognito User Pool using client_credentials grant and adding is to the request to origin as an Authorization header.

Due to limitations on Lambda@Edge uses inline client secret instead of encrypted environment variables.

To keep package size to minimum I use native node libraries to make an http request.

To reduce pressure on Cognito `accessToken` is stored outside of the handler - this will allow to reuse token if function runs on the same container multiple times within container lifetime.

```
const querystring = require("querystring");
const https = require("https");

const cognitoUrl = "<domain-name>.auth.<region>.amazoncognito.com",
  cognitoClientId = "<client_id>",
  cognitoClientSecret = "<client_secret>";

var accessToken;

const parseJwt = token => {
  try {
    return JSON.parse(
      Buffer.from(token.split(".")[1], "base64").toString("binary")
    );
  } catch (e) {
    return null;
  }
};

// Get AccessToken from Cognito

const getAccessToken = async (cognitoClientId, cognitoClientSecret) => {
  const secret_token = new Buffer.from(
    `${cognitoClientId}:${cognitoClientSecret}`
  ).toString("base64");

  return await new Promise((resolve, reject) => {
    var postData = querystring.stringify({
      grant_type: "client_credentials"
    });

    var options = {
      host: cognitoUrl,
      port: 443,
      method: "POST",
      path: "/oauth2/token",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        "Content-Length": postData.length,
        Authorization: `Basic ${secret_token}`
      }
    };

    var req = https.request(options, function(res) {
      var result = "";
      res.on("data", function(chunk) {
        result += chunk;
      });
      res.on("end", function() {
        result = JSON.parse(result);
        resolve(result.access_token);
      });
      res.on("error", function(err) {
        console.log(err);
        reject(err);
      });
    });

    // req error
    req.on("error", function(err) {
      console.log(err);
      reject(err);
    });

    //send request witht the postData form
    req.write(postData);
    req.end();
  });
};

exports.handler = async (event, context) => {
  const request = event.Records[0].cf.request;
  request.uri = "/";

  if (
    typeof accessToken === "undefined" ||
    new Date().getTime() / 1000 > parseJwt(accessToken).exp
  ) {
    accessToken = await getAccessToken(cognitoClientId, cognitoClientSecret);
  }

  request.headers.authorization = [
    { key: "Authorization", value: accessToken }
  ];

  return request;
};
```
