### ISSUE TITLE
Any way to NOT limit query?

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws/aws-appsync-community#53]
Can we do a query that returns ALL result without pagination?

#### Current workaround

```js
import { API, graphqlOperation } from 'aws-amplify';
import { listItems } from '../../graphql/queries';

export default async () => {
  let nextToken = null;
  let items = [];

  do {
    const result = await API.graphql(graphqlOperation(listItems, {
      nextToken
    }));

    items = items.concat(result.data.listItems.items);
    nextToken = result.data.listItems.nextToken;
  } while (nextToken);

  return items;
}
```

The code above continually fetch until nextToken is `falsy`.

**Comment by itrestian** [comment]
Only way I can think of is by using a lambda data source that you use to query DynamoDb yourself and follow the nextToken in the lambda itself. The AppSync resolvers for DynamoDb data sources are just wrappers around the corresponding DynamoDb Scan/Query operations.

**Comment by GitHubPhongNguyen** [comment]
I also had the same problem as you. I don't know if you have an optimal way to handle this?

**Comment by sascha93** [comment]
Not the best way, but you can use subscriptions.

Trigger a lambda from the client-side, make a scan against your table (keep an eye that you maybe have here also pages) and send it in parallel (async) via subscription back to the client.

Also, keep an eye on it, that sending data back to the client is not as easy as it sounds. :) You have to generate an API key, and trigger a separate mutation directly from your backend.

I've implemented this, it took me about 1–2 days. Perhaps can be expensive, but is an idea :)
