### ISSUE TITLE
Feature Request: non-expiring api key for unauthenticated users

### ISSUE THREAD

**Issue by stefangomez** [aws/aws-appsync-community#57]
I know this has been brought up many times in [many](https://github.com/aws-amplify/amplify-cli/issues/1576#issuecomment-507467641), [different](https://github.com/aws/aws-appsync-community/issues/50), [ways](https://github.com/aws/aws-appsync-community/issues/1), but I don't think I've heard an official response from AWS on how to solve this seemingly common problem, so I wanted to bring it back up in another forum.

**The problem:**
Public access to the AppSync GraphQL API without the need to re-deploy a web app, or worse yet recompile, distribute, face re-approval submission in relevant app stores (with highly variable processing times).

The current problem stems from the fact that API Keys for AppSync MUST expire. I haven't encountered it **yet**, but I know I will. It's troubling to me that in choosing to build a mobile app, using AppSync as the backend, I know that I will HAVE TO update my app solely to update the API KEY upon its expiry. This sucks. I get that an update/year shouldn't be a big deal, but it just adds to the friction and processes in an otherwise normal mobile app (or even web app) development process.

There are many "workarounds" out there. You could use AWS_IAM w/cognito pools like I outlined [here](https://github.com/aws-amplify/amplify-cli/issues/1576#issuecomment-507467641), but I don't think you should necessarily be forced to use Cognito for this, and yet still, it's a workaround. Another is using a Lambda@Edge ([source](https://github.com/aws/aws-appsync-community/issues/50)) on Cloudfront... and I'm sure there are others.

@ AWS - do you have a plan for either allowing an un-expiring API Key, or some other (maybe even better) solution to this? 

Thank you, and please don't see this as "yet another complaint from this guy..." -- I love AppSync (and Amplify as well) so I just want to see it get better! Thanks :)

**Comment by undefobj** [comment]
Hi just to clarify one thing, the API Keys in AppSync can actually be extended for up to a year so you don't have to re-deploy your app. Even if it's the last day you can extend them for another year.

**Comment by stefangomez** [comment]
Awesome. I do see that page now. for others reference: https://docs.aws.amazon.com/appsync/latest/devguide/security.html 

Might be good to link to that from the Amplify docs as well.

I guess that only leaves a few questions. Are there any limits to extending? like..are there limits on how many times/how often you can extend? Are there any plans to have an 'auto-extend' option? I guess it could be easy enough to write a script to do this so long as we avoid any possible limits there are.

Thanks!

**Comment by itrestian** [comment]
There are currently no limits to how many times they can be extended, you can extend a key any times you want. You can basically write a cron cloudwatch event that triggers a lambda that just updates the key upon expiry.

**Comment by stefangomez** [comment]
awesome. good to know. thanks! going to close my issue for now since it's not relevant anymore.
