### ISSUE TITLE
Bug? multiple inheritance

### ISSUE THREAD

**Issue by timo92** [aws/aws-appsync-community#58]
GraphQL allows objects to [implement multiple interfaces](https://graphql.github.io/graphql-spec/June2018/#ImplementsInterfaces) by joining their names with & (ampersand). Creating schemas containg ampersands (using the console or aws cli) fails with a syntax error on the ampersand character. When separating the interfaces with a comma the schema is accepted and seems to yield the result expected from multiple inheritance. Sadly I cannot find this syntax in the spec.

Is this intended behavior or an incorrect implementation of the graphql specification?

```
interface Named {
  name: String!
}

interface Numeric {
  value: Int!
}

type NamedInt implements Named & Numeric {
  name: String!
  value: Int!
}

type Query {
  test: NamedInt!
}
```
yields: Syntax Error GraphQL request (9:32) Cannot parse the unexpected character "&". 8: 9:

**Comment by tinnou** [comment]
Hello,

Thank you for reporting the issue. I could confirm this is happening in the AppSync console. However using the AWS CLI I was able to use both ampersand and comma. 

Command: 
```
aws appsync start-schema-creation --api-id XXX --definition "interface Node {id: ID! } type Post implements Thing & Node {id: ID! title: String } type Query {getPost: Post } interface Thing {id: ID! title: String }"
```
and
```
aws appsync start-schema-creation --api-id XXX --definition "interface Node {id: ID! } type Post implements Thing, Node {id: ID! title: String } type Query {getPost: Post } interface Thing {id: ID! title: String }"
```
work.

I was able to verify the output using the following command:
```aws appsync get-introspection-schema --api-id XXX --format SDL ./out.graphql```

**Comment by timo92** [comment]
Thank you for looking into this.
You are right, I can no longer reproduct this either

**Comment by ibraelillo** [comment]
I'm still facing this issue, and it's happening in the CDK and in the console also. Commas works in the console, but not on the CDK deployment.  '&' seems not to work in any case.
