### ISSUE TITLE
number of requests

### ISSUE THREAD

**Issue by rudyhadoux** [aws/aws-appsync-community#6]
Hi,

Is it possible to know WITH A GRAPHQL REQUEST the number of requests (including subscriptions) in a month with by example the attribute id = one_id ? Whithout using CloudTrail or Cloudwatch.  My goal is to count for pricing.

**Comment by AaronHarris** [comment]
For fine-grained metrics like this, you'll need to use CloudWatch. Do you need help finding these metrics using CloudWatch?

**Comment by rudyhadoux** [comment]
Thanks @AaronHarris.

I thought about adding an counter attribute to increment number of requests but impossible to increment for subscriptions... That is my problem.

If there is an easy way to know monthly number of requests for an ID with CloudWatch logging (and a lambda request), I indeed search informations for that...

**Comment by rudyhadoux** [comment]
Can a subscription update an attribute ?
