### ISSUE TITLE
X-Ray support

### ISSUE THREAD

**Issue by yvele** [aws/aws-appsync-community#62]
I've enabled X-Ray on my Lambda resolvers, but it would be nice if X-Ray knows about resolvers, pipeline functions, and why not sub-resolvers that are related to the same root request.

Because actually it looks like unrelated services

![image](https://user-images.githubusercontent.com/4225430/66501756-48f4c080-eac4-11e9-8fc8-e0442133fe5e.png)

e.g. all the AppSync services for a single GraphQL API should come from a single entry point 🤔 

Edit: Related AWS forum post https://forums.aws.amazon.com/thread.jspa?messageID=901150#901150

**Comment by AaronHarris** [comment]
@yvele Thanks for the comment. We have prioritized this request and will announce when we release support for AWS X-ray.

**Comment by MatejBalantic** [comment]
any updates? We'd love to see this feature

**Comment by AaronHarris** [comment]
We can't comment on future roadmap dates, but rest assured we are working on this request.

**Comment by tinnou** [comment]
We just released X-Ray support for AppSync APIs. More details on how to enable it and what is being traced here https://docs.aws.amazon.com/appsync/latest/devguide/x-ray-tracing.html

**Comment by tinnou** [comment]
Feature has been released 823d9c6 , closing.
