### ISSUE TITLE
multi auth doesn't handle @model directive

### ISSUE THREAD

**Issue by hirochachacha** [aws/aws-appsync-community#63]
I want to use OPEN_ID CONNECT for user authentication. 
In addition, I also want to keep some queries accessible for anyone.
It seems to me that I can use API_KEY for the latter case with multiple authorization.
Then I encountered the problem. In order to make everything works, I have to annotate most types which are supposed to be generated automatically.
Are there any solutions? Thanks.

**Comment by mikeparisstuff** [comment]
The CLI packs some multi-auth functionality out of the box and can be read more under the @auth directive here: https://aws-amplify.github.io/docs/cli-toolchain/graphql. Have you tried using multiple auth rules with different providers as mentioned in those docs? Also for CLI specific questions you will likely have better luck getting issues answered if posted here: https://github.com/aws-amplify/amplify-cli/issues.

You always have an option to use IAM auth mode & Amazon Cognito Identity Pools if you want another way to allow access to "unauthorized" (think public) identities. The identity pools option adds a few more layers of defense over the API Key but takes a bit more time to setup.

**Comment by hirochachacha** [comment]
Thank you for your suggestions. I found the same issue is open at https://github.com/aws-amplify/amplify-cli/issues/2673 . I close this one.
