### ISSUE TITLE
AppSync Dart/Flutter SDK?

### ISSUE THREAD

**Issue by doc-rj-celltrak** [aws/aws-appsync-community#66]
AppSync is great, and so is Flutter. How about a Dart SDK? Anyone know of AWS plans around Flutter, if any? That would be a game changer. So many drawbacks to using platform channels, like this sample does: https://github.com/ineat/flutter-aws-appsync-sample

**Comment by tinnou** [comment]
We don't typically share plans but that's good feedback. I'll share this feature request with the team.

**Comment by doc-rj-celltrak** [comment]
Thanks @tinnou, much appreciated. That's all I can ask, but from what I've seen and heard, there are many users like myself who want a good offline-first sync solution like AppSync on Flutter. Dart has some things in common with Javascript, so a port might not be too bad.

**Comment by tinnou** [comment]
Also there is an ongoing issue you can +1 for Flutter support in amplifiy-js https://github.com/aws-amplify/amplify-js/issues/1852

**Comment by doc-rj-celltrak** [comment]
Thanks, I added my thumbs up there.

**Comment by iapicca** [comment]
> Also there is an ongoing issue you can +1 for Flutter support in amplifiy-js [aws-amplify/amplify-js#1852](https://github.com/aws-amplify/amplify-js/issues/1852)

Hi @tinnou 
the issue you linked doesn't appear to have any recent activity from the team
and according to this [issue](https://github.com/aws-amplify/docs/issues/765)
in July there was no plan to implement the feature. 
Is there any active plan or milestone regarding this feature now?
Thank you

**Comment by katzeforest** [comment]
Sorry we don't typically share plans. Please follow up on our launch announcement to see latest feature release. :)

**Comment by zhongwen-unnoo** [comment]
+1

**Comment by dtelaroli** [comment]
+1

**Comment by devDeejay** [comment]
Waiting!!!!

**Comment by vishal-android-freak** [comment]
https://github.com/agnostech/flutter_amplify

We are building the entire Flutter Plugin Stack for the Amplify SDK. It's very early days and we have added Cognito support. Feel free to send PRs and contribute. Expect the documentation to go live in the next 2-3 days :) The Cognito package will be released on pub.dev this week. Cheers!

**Comment by YassineRjl** [comment]
Any official news on this?

**Comment by nguyenxndaidev** [comment]
Unfortunately, I have to make a difficult decision to choose between **Flutter/Firebase** and **NoFlutter/AppSync**.
It seems that AppSync for Dart/Flutter will not be supported soon, I must go with **Flutter/Firebase**. Cannot wait, very sad :-(.

**Comment by undefobj** [comment]
Flutter is coming, please see the following: https://github.com/aws-amplify/amplify-js/issues/1852#issuecomment-641560886

**Comment by ash007osh** [comment]
Seems like no appsync plugin yet for Flutter... It's been long wait 👍

**Comment by yukitaka13-1110** [comment]
Any news about amplify-flutter?

**Comment by devDeejay** [comment]
I think developers can get started building Flutter apps with AWS backend using their latest released Amplify SDK

Release News: https://aws.amazon.com/blogs/aws/amplify-flutter-is-now-generally-available-build-beautiful-cross-platform-apps/

Integration Documentation - https://docs.amplify.aws/start/getting-started/nextsteps/q/integration/flutter

**Comment by jpignata** [comment]
As @devDeejay noted, this has shipped!
