### ISSUE TITLE
Connection resolving in pipeline resolver

### ISSUE THREAD

**Issue by Rodiot89** [aws/aws-appsync-community#67]
Consider the following graphql schema:
```
type Post @model {
    id: ID!
    title: String!
    comments: [Comment] @connection(name: "PostComments", sortField: "createdAt")
}
type Comment @model {
    id: ID!
    content: String!
    post: Post @connection(name: "PostComments", sortField: "createdAt")
    createdAt: String
}
```
From within a pipeline resolver I can query the Post type with a function, which data source is connected to the Post table.
How do I then proceed to query the associated comments as they are not returned by the query?
To find out more, I ran some normal sample queries like 
```
query GetPostAndComments {
    getPost(id: "...") {
        id
        title
        comments {
          items {
            content
            createdAt
          }
        }
    }
}
```
and looked through the cloudwatch logs.
It seems that the Appsync backend is invoking the correct resolvers attached to the connection automatically based on the issued query.
How can I do this from within a pipeline resolver?

**Comment by Rodiot89** [comment]
I looked through the logs once more and probably found the solution in  form of a request template
```
{
"version":  "2017-02-28 ",
 "operation": "Query",
 "query":   {"expression": "#connectionAttribute = :connectionAttribute",
                 "expressionNames":{"#connectionAttribute":"postCommentId"},
                 "expressionValues":{":connectionAttribute":{"S":"a"}}},  
  "scanIndexForward":   true ,
  "filter":   null  ,
  "limit": 10,
  "nextToken":   null ,
"index":  "gsi-CreatedConnection"
}"
```
Maybe this should be part of a tutorial, i.e.
https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-pipeline-resolvers.html

**Comment by avlonder** [comment]
Hi @Rodiot89, I came across this issue as well, but my situation is a bit more complicated: in my pipeline resolver, I am looping over different posts (which I got with a batchGetItem) and then querying the comments attached to each of these posts, but as you know post.comment is null. Have you, by any chance, found any solution for this?

**Comment by jpignata** [comment]
Thank you for sharing your solution! Let us know if we can help here.
