### ISSUE TITLE
Revoked access token still allows authorization

### ISSUE THREAD

**Issue by alecwcp** [aws/aws-appsync-community#68]
When interacting with App Sync using Cognito User Pools for authorization, the app provides the access token to authorize when making the request. If we use the cognito-idp cli `admin-user-global-sign-out` to revoke all access tokens (as indicated here https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html#amazon-cognito-identity-user-pools-revoking-all-tokens-for-user) the app is still able to authenticate with App Sync using the same access token even though it should be invalid.

We're unclear if this is an issue with revoking the access token in Cognito, or a check that needs to happen within App Sync (or whether we should be checking this somehow within the resolvers).

If this should be raised somewhere else with Cognito rather than App Sync I would be grateful if someone could point me at the correct place to raise this.

**Comment by katzeforest** [comment]
Can you try to do the following to let us know is it a bug on AppSync?

1) authenticate and get access token
2) call the global sign out api to invalidate the token
3) now use that token from step 1 that was invalidate to call an authenticated api like “get-user” which takes an access token as input 
4) if 3rd step succeeds then bug on Cognito
5) otherwise there’s a chance the bug is on AppSync and we need to investigate further

**Comment by alecwcp** [comment]
Hi @katzeforest 

Thanks for investigating and the clear explanation.
I don't think there is anything more to do here - as you say, the access token is still valid because the signature is still intact (thanks for the doc link, I hadn't previously understood just how AppSync was checking the token with Congito).

I don't have any additional functionality to request / issues to raise with the Cognito team currently, but if I did what would be the best channel for that? (I couldn't find an equivalent GitHub repo to this one for Cognito).

**Comment by katzeforest** [comment]
You can use the [aws forum](https://forums.aws.amazon.com/) as channel to contact Cognito team. :)
