### ISSUE TITLE
Sorting by date. Are there changes that need to be made to schema.graphql?

### ISSUE THREAD

**Issue by cottageGrove** [aws/aws-appsync-community#69]
What are some of the changes I need to make to the graphql schema to allow for sorting by date on graphql. There doesn't seems to be any filter by date. Will this be a feature down the line? 

Attached an image of schema.graphql
<img width="823" alt="Screen Shot 2019-11-18 at 10 04 28 AM" src="https://user-images.githubusercontent.com/17324193/69063602-d04e2180-09ea-11ea-8d0c-5345ddf18168.png">

**Comment by katzeforest** [comment]
AWS AppSync allow you to specify scanIndexForward as a property in the request mapping template. You can specify true (ascending) or false (descending) traversal of the index based on the sort key.

**Comment by cottageGrove** [comment]
@katzeforest Kinda clueless. Is this in the AppSync GUI on console.aws?

**Comment by Sunac** [comment]
@cottageGrove you can specify scanIndexForward, like @katzeforest mentioned, in your request mapping template no mater is it serverless project or in AWS AppSync console -> request mapping template.
If your dynamoDB has GSI where your date is sort key you can simply build query in your request mapping template like this:
{   
    "version" : "2017-02-28",
    "operation" : "Query",
    "index": "Your index",
    "query" : {
        ...
    },
    "scanIndexForward" : false,                     // or true
    "filter" : {
       ...
    }
}

**Comment by cottageGrove** [comment]
@Sunac thanks. I'll look into this and get back to you. Is there no way to modify the schema.graphql file instead?

**Comment by Ricardo1980** [comment]
you can create you own enum (for example, SortingMethod) with different sorting criteria (asc, desc, bigger, smaller, nearby...) and then add a sortingMethod field to your Query.
In the resolver, you translate that properly according the db system you are using.

**Comment by tinnou** [comment]
I'm marking the question as answered, feel free to reopen the issue if needed.
