### ISSUE TITLE
Cannot convert from binary to hex in the request resolver

### ISSUE THREAD

**Issue by Ricardo1980** [aws/aws-appsync-community#75]
Hello, I have a problem I don't know how to fix, can you help me?

My data model has a table and that table has BINARY(16) as primary key, another one for a foreign key.

<img width="1112" alt="Screenshot 2019-12-11 at 21 24 02" src="https://user-images.githubusercontent.com/738681/70662959-397a2b00-1c5f-11ea-9b0e-1b0bbb0fe084.png">

If I create a resolver that returns everything in the response, using "select * from ....", it appears it works:
<img width="1291" alt="Screenshot 2019-12-11 at 21 13 20" src="https://user-images.githubusercontent.com/738681/70663019-5c0c4400-1c5f-11ea-8adb-be5dc00e70d2.png">

But the result is not formated properly, I want to receive that binary(16) as hex, instead of this:
<img width="1033" alt="Screenshot 2019-12-11 at 21 20 58" src="https://user-images.githubusercontent.com/738681/70663070-77774f00-1c5f-11ea-8b1f-939daca81bdf.png">

This is the format I want to use:
<img width="1100" alt="Screenshot 2019-12-11 at 21 22 14" src="https://user-images.githubusercontent.com/738681/70663111-94138700-1c5f-11ea-99fd-630528d837ae.png">

If instead of using "select * from...", I return all fields and I apply HEX, like the command I used in the previous screen, using the Query Editor in RDS:
<img width="1288" alt="Screenshot 2019-12-11 at 21 12 59" src="https://user-images.githubusercontent.com/738681/70663186-b9a09080-1c5f-11ea-9030-2fbcb942964a.png">

It does not work, I see this strange error:
<img width="1028" alt="Screenshot 2019-12-11 at 21 21 35" src="https://user-images.githubusercontent.com/738681/70663208-c91fd980-1c5f-11ea-8338-76c9f8c6c075.png">

I don't know what's going on.
Do you see any problem in my approach? Thanks a lot for your time.

**Comment by itrestian** [comment]
my hunch is that you would have to alias the hexed column to the particular GraphQL field you want it to fit in?

**Comment by Ricardo1980** [comment]
Thanks @itrestian 
Can you elaborate that?
Do you mean I should modify the generated API.swift file? (all the access methods, seems a terrible idea)
Do you know what's going and why I cannot use in the second clause? Do you see another workaround?

It seems the problem is HEX, because if I remove but I leave all the fields instead of *, it works:

<img width="1289" alt="Screenshot 2019-12-11 at 22 31 26" src="https://user-images.githubusercontent.com/738681/70666214-1f901680-1c66-11ea-89d1-372dfc1f66be.png">

<img width="1042" alt="Screenshot 2019-12-11 at 22 31 18" src="https://user-images.githubusercontent.com/738681/70666226-261e8e00-1c66-11ea-9174-03b09faddc04.png">

Thanks a lot for your help :)

**Comment by itrestian** [comment]
I meant when you do the select you alias the hex such as below

select hex(userChangeRequestId) as requestId and have the graphql field named requestId for example.

**Comment by Ricardo1980** [comment]
Hey @itrestian , your solution works, even if I use the same as an alias, which is even better! Thanks a lot for your help!

![Screenshot 2019-12-12 at 00 12 10](https://user-images.githubusercontent.com/738681/70671613-874d5e00-1c74-11ea-97ed-8e85b9c9c41f.png)

![Screenshot 2019-12-12 at 00 16 09](https://user-images.githubusercontent.com/738681/70671645-a4822c80-1c74-11ea-8d12-10faf37765e5.png)
