### ISSUE TITLE
Caching CloudFormation bug ?

### ISSUE THREAD

**Issue by bboure** [aws/aws-appsync-community#76]
Hi, 

There might be a bug in cloudformation with the new Caching feature. I am unable to disable caching for a resolver after enabling it.

How to reproduce?

If I deploy a stack using the following template:

````json
// ...
	{
      "Type": "AWS::AppSync::Resolver",
      "Properties": {
        "Kind": "UNIT",
        "TypeName": "Query",
        "FieldName": "fieldName",
        "RequestMappingTemplate": "...",
        "ResponseMappingTemplate": "...",
        "CachingConfig": {
          "Ttl": 60
        },
		...
      }
    },
// ...
````

The resolver gets properly created with the caching enabled and a `60` ttl.

However, **removing** `CachingConfig` does not seem to have the opposite effect.
The resolver still has caching enabled in the console after re-deploying.

I tried setting `CachingConfig` to an empty Object or `null`, and `Ttl` to `null` without any luck.

Am I doing something wrong or can you confirm a bug in Cfn?

Thank you

**Comment by rakeshmenon** [comment]
+1

**Comment by itrestian** [comment]
Yes, you are correct, it is a bug. We have deployed the fix to us-east-2 for now and it will be available in other regions shortly

**Comment by itrestian** [comment]
This should be fixed across all regions at this point.
