### ISSUE TITLE
How to configure the new Pure Websockets with the AWS AppSync JavaScript SDK?

### ISSUE THREAD

**Issue by wimvdb** [aws/aws-appsync-community#77]
How to configure the new [Pure Websockets](https://aws.amazon.com/blogs/mobile/appsync-realtime/) with the AWS AppSync JavaScript SDK?

**Comment by elorzafe** [comment]
@wimvdb You just need to use the latest AppSync SDK JS to start using it.

**Comment by wimvdb** [comment]
@elorzafe Thank you for answering

Just to be clear, even though my config is configured to use a url with https like:

```
 appSyncConfig: {
        url: 'https://xxxxxxxx.appsync-api.eu-west-1.amazonaws.com/graphql',
        region: 'eu-west-1',
        ...
}
```
I'm automatically using the Pure websockets as long as I use  "aws-appsync": "3.x.x?

**Comment by elorzafe** [comment]
Yes, you can check the network connection on your dev tools (name is graphql?header=....)

**Comment by wimvdb** [comment]
Thanks a lot!! 
I see it now. I still had to enable the Network Inspect in the react native debugger and also add some code in my app to see websockets.

```
//in App.js
React.useEffect(() => {
            GLOBAL.XMLHttpRequest = GLOBAL.originalXMLHttpRequest || GLOBAL.XMLHttpRequest
            GLOBAL.WebSocket = GLOBAL.originalWebSocket || GLOBAL.WebSocket
    }, []);
```
