### ISSUE TITLE
Question: HTTP DataSource/Resolver to SQS endpoint

### ISSUE THREAD

**Issue by darrenfurr** [aws/aws-appsync-community#78]
I'm trying to invoke a query or mutation that does a SendMessage to SQS. It seems like this should be possible, but I'm not having any luck.

Repro steps:
- Create SQS queue
- Create HTTP Datasource to SQS endpoint with Role that has SQS:SendMessage policy attached:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "sqs:*"
            ],
            "Effect": "Allow",
            "Resource": [
                "<sqs arn>"
            ]
        }
    ]
}
```

- Add Resolver to Query
- DataSource, specify HTTP
- Request template:
```
{
    "version": "2018-05-29",
    "method": "GET",
    "resourcePath": "/",
    "params":{
        "query": {
        "Action": "SendMessage",
        "MessageBody": "test message",
        "MessageGroupId": "group-id"
        },
        "headers":{
            "Authorization": "$ctx.request.headers.Authorization"
        }
    }
}
```

Except when I do ALL of this, I get a 403. I think because the Resolver Arn doesn't have the appropriate permissions to write to SQS.
```
"statusCode": 403,
"body": "<?xml version=\"1.0\"?><ErrorResponse xmlns=\"http://queue.amazonaws.com/doc/2012-11-05/\"><Error><Type>Sender</Type><Code>AccessDenied</Code><Message>Access to the resource https://sqs.us-east-1.amazonaws.com/ is denied.</Message><Detail/></Error><RequestId>5c692364-b89e-5cc4-bbc0-75ed121d34e1</RequestId></ErrorResponse>"
```

It seems like what I am attempting should be possible, but am I way off base?

**Comment by itrestian** [comment]
You also need to specify that AppSync is allowed to assume the role:

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "appsync.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}`

Have a look at the docs: https://docs.aws.amazon.com/appsync/latest/devguide/security.html

**Comment by darrenfurr** [comment]
Yep. Did that too...on the role with the policy to write to SQS
![Screen Shot 2020-01-03 at 3 30 50 PM](https://user-images.githubusercontent.com/133894/71750457-0c73ff00-2e3e-11ea-9a7f-8c1ec6fce91e.png)

**Comment by itrestian** [comment]
I believe if you use a GET method, you would need to specify the parameters for the request in the resourcePath. If you go the POST way, you can do something similar to here where you specify the sendmessage parameters as stringified JSON in the body.

https://aws.amazon.com/blogs/mobile/invoke-aws-services-directly-from-aws-appsync/

**Comment by darrenfurr** [comment]
Let me give the GET a try again using the parameters in the resource path. I tried a POST, but I could not use Content-Type: `x-www-form-urlencoded` in the Resolver.

**Comment by darrenfurr** [comment]
@itrestian - I have not had an opportunity to come back to this. In fact, we switched to using SNS. So you can close this for now.

**Comment by bvand** [comment]
I'm also having trouble using SQS with AppSync, ending up with `AccessDenied`. The problem seems to be that there aren't any authentication params added to the HTTP request.  I've verified this by sending the request to a dummy API Gateway endpoint to capture it. Only the `Action` and `MessageBody` query params end up in the request.

@itrestian What configuration ends up getting AppSync to actually sign the request as the service role? I think you're right about not having to use the `Authorization` header - if that is added in the request template, it ends up signing with `appsync` e.g. `Credential=<access_key>/20200404/us-east-1/appsync/aws4_request`. This auth param is not one that can be used for SQS because the service is incorrect.

Here is my configuration:
**SQS queue**
```
{
    "QueueUrls": [
        "https://queue.amazonaws.com/<acct_id>/queue"
    ]
}
```
**HTTP DataSource**
```
{
    "dataSource": {
        "dataSourceArn": "arn:aws:appsync:us-east-1:<acct_id>:apis/<api_id>/datasources/SqsHttpDataSource",
        "name": "SqsHttpDataSource",
        "type": "HTTP",
        "serviceRoleArn": "arn:aws:iam::<acct_id>:role/appsync-sqs",
        "httpConfig": {
            "endpoint": "https://sqs.us-east-1.amazonaws.com/<acct_id>",
            "authorizationConfig": {
                "authorizationType": "AWS_IAM",
                "awsIamConfig": {
                    "signingRegion": "us-east-1",
                    "signingServiceName": "sqs"
                }
            }
        }
    }
}
```

**IAM Role with Trust Policy**
```
{
    "Role": {
        "Path": "/",
        "RoleName": "appsync-sqs",
        "RoleId": "<role_id>",
        "Arn": "arn:aws:iam::<acct_id>:role/appsync-sqs",
        "CreateDate": "2020-03-30T14:31:04Z",
        "AssumeRolePolicyDocument": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {
                        "Service": "appsync.amazonaws.com"
                    },
                    "Action": "sts:AssumeRole"
                }
            ]
        },
        "Description": "",
        "MaxSessionDuration": 3600,
        "RoleLastUsed": {}
    }
}
```

**IAM Policy**
```
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "All",
			"Effect": "Allow",
			"Action": [
				"sqs:*"
			],
			"Resource": "*"
		}
	]
}
```

**Request Template**
```
{
    "version": "2018-05-29",
    "method": "GET",
    "resourcePath": "/queue",
    "params":{
        "query": {
        	"Action": "SendMessage",
        	"MessageBody": "test"
        }
    }
}
```

**Response**
`Access to the resource https://sqs.us-east-1.amazonaws.com/queue is denied.`

**Comment by cm-iwata** [comment]
@darrenfurr
@bvand

I can use SQS send message with  HTTP datasource and post request.

Here is my CFn template.

```
AWSTemplateFormatVersion: '2010-09-09'
Description: AppSync Service Proxy Sample
Resources:
  ProxyApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      AuthenticationType: API_KEY
      Name: AppSync Service Proxy API
  ProxyApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt ProxyApi.ApiId      
  MessagesSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt ProxyApi.ApiId
      DefinitionS3Location: schema.graphql
  AppSyncServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com
      Policies:
        - PolicyName: proxy-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: "*"      
  SQSQueue:
    Type: AWS::SQS::Queue            
  SQSSendMsgDs:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt ProxyApi.ApiId
      Name: SQSSendMessageDataSource
      Type: HTTP
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      HttpConfig:
        Endpoint: !Sub https://${AWS::Region}.queue.amazonaws.com/
        AuthorizationConfig:
          AuthorizationType: AWS_IAM
          AwsIamConfig:
            SigningRegion: !Ref AWS::Region
            SigningServiceName: sqs
  SQSSendMsgMutationResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt ProxyApi.ApiId
      TypeName: Mutation
      FieldName: sendMessage
      DataSourceName: !GetAtt SQSSendMsgDs.Name
      RequestMappingTemplate: !Sub |
        #set($action = "Action=SendMessage")
        #set($version = "Version=2012-11-05")
        #set($queueurl = "QueueUrl=${SQSQueue}")
        #set($msgbody = "MessageBody=$ctx.arguments.data")

        {
          "version": "2018-05-29",
          "method": "POST",
          "resourcePath": "/",
          "params": {
            "headers": {
              "Content-Type": "application/x-www-form-urlencoded"
            },	
            "body": "$action&$version&$queueurl&$msgbody"
          }
        }
      ResponseMappingTemplate: |
        #if($ctx.result.statusCode == 200)
            $utils.xml.toJsonString($ctx.result.body)
        #else
            $utils.appendError($utils.xml.toJsonString($ctx.result.body), "$ctx.result.statusCode")
        #end  
```
Here is my GraphQL schema.
```
type Query {
	search(text: String): String
}

type Mutation {
	sendMessage(data: String): String
}

schema {
	query: Query
	mutation: Mutation
}
```
FYI,  Here is my blog post.
https://dev.classmethod.jp/articles/appsync-for-aws-service-proxy/

**Comment by bvand** [comment]
@cm-iwata thank you! I was able to get this working with your CloudFormation and a few small tweaks:
* Define `MessagesSchema` inline instead of from S3 (either will work of course)
* Change `HttpConfig.Endpoint` to `!Sub https://sqs.${AWS::Region}.amazonaws.com/`

There's an added complication for FIFO queues - you have to include `MessageGroupId` (see API [docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessage.html))
