### ISSUE TITLE
AWS AppSync auto-scaling

### ISSUE THREAD

**Issue by rudyhadoux** [aws/aws-appsync-community#8]
Hi, is the auto-scaling setup of DynamoDB  enough for AppSync auto-scaling ?

**Comment by mikeparisstuff** [comment]
Hello, I'm not sure I fully understand the question. You can use an auto-scaling enabled DynamoDB table with AppSync and as your API traffic increases, so to will the IOPS of the table if configured correctly. You may also use the PER_REQUEST billing mode in DynamoDB which removes the need for the auto-scaling config. You do not need to worry about configuring auto-scaling for AppSync as the service manages scale for you but you should keep in mind the AppSync limits https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html.

**Comment by rudyhadoux** [comment]
That answers my question. Thanks.
