### ISSUE TITLE
Could not determine the exact type of interface. Expected MAP/OBJECT type.

### ISSUE THREAD

**Issue by cthomaschase** [aws/aws-appsync-community#84]
Not sure this is the correct repo for this issue.

In my schema, I have the following

``` graphql

type Account {
  id: ID!
  name: String!
  integration: Integration
}

interface Integration {
  type: IntegrationType!
}

type WebIntegration implements Integration {
  type: IntegrationType!
  name: String
} 

enum IntegrationType {
  WEB
  DESKTOP
}

query accounts {
  accounts {
    id
    name
    integration {
      ... on WebIntegration {
        type
        name
      }
    }
  }
}
```

I'm using AppSync with an RDS resolver to Postgres. When I run this query, I get the following:

``` js
{
  "errors": [
    {
      "errorType": "BadRequestException",
      "message": "Could not determine the exact type of Integration. Expected MAP/OBJECT type.'"
    }
  ]
}
```

Previously, when storing the data in DynamoDB, I was able able to solve this by adding `"__typename" : "WebIntegration"` to each Integration JSON document returned in the response mapping template.

Any thoughts on how to handle?

**Comment by Ricardo1980** [comment]
Hey @cthomaschase 

I have a question regarding your question :)

I see you have a one-to-one relationship between an account and integration. 
I also see you are using RDS, that is, SQL. 

How does your response mapping template look like?

I was told by amazon that @connection (or nested types) is not supported when using RDS data sources. 
https://github.com/aws-amplify/amplify-cli/issues/3120

I had this problem and this is what I did:
In my request mapping I have a SQL query that gets all the info, but plain structure. In my response mapping, I process the info to create the nested structure. 
This is crappy because I have to to this manually all the time, the query perhaps retrives info that graphql is not asking for, and mappings, especially the response mapping, are more complex. 

Perhaps, another possibility is to send 2 sql queries in the request (the first one is the root type and the second one is the relationship using the identifier passed by the gql query), then put them together in the response mapping. 
It seems to me this is also too complex.  

How did you solve this?

Thanks a lot.

**Comment by cthomaschase** [comment]
@Ricardo1980 thanks for the followup.

The integration object is stored as JSON in the account table, so it makes sense that the nested type is not being processed properly.

I've confirmed that the issue is in fact that the JSON object does not have the appropriate `__typename` value. I confirmed this by removing the field from the original resolver and creating a separate resolver directly on the integration field in AppSync. When I do that, I get the error:

``` js
{
  "errors": [
    {
      "errorType": "BadRequestException",
      "message": "Could not determine the exact type of Integration. Missing __typename key on value.'"
    }
  ]
}
```

My current response mapping looks like this

`$utils.toJson($utils.rds.toJsonObject($ctx.result)[0]) `

I now need to figure out how to retrieve and modify the JSON from the response and add the `__typename` value.

**Comment by Ricardo1980** [comment]
Do you mean that you are saving a json string inside a field of a relational database?

**Comment by cthomaschase** [comment]
Yes, because it's an interface (and the fields change by implementation) I'm storing the JSON inside a field in postres as type json.

**Comment by Ricardo1980** [comment]
I have never see a json string inside a field.
Anyway, if you want to convert that to the proper structure, you have to assemble it by yourself.

Here you can see mine, my response mapping. There is a LIKE and inside every like, there is one USER.
Do something similar:

```
#if($ctx.error)
    $utils.error($ctx.error.message, $ctx.error.type)
#end

## remove the user limit+1, we only want that one to get the token for the next page, if it exists
#set($fullLikes = $utils.rds.toJsonObject($ctx.result)[0])
#set($likes = [])
#foreach ($fullLike in $fullLikes)
	
    #if($foreach.count == $ctx.args.limit + 1)
        #set($nextToken = $fullLike.nextToken)
    #else 
    	#set($user = {})
		$util.qr($user.put("lastHeartbeat", $fullLike.lastHeartbeat))
		$util.qr($user.put("occupation", $fullLike.occupation))
		$util.qr($user.put("type", $fullLike.type))
		$util.qr($user.put("createdAt", $fullLike.createdAt))
		$util.qr($user.put("primaryCityId", $fullLike.primaryCityId))
		$util.qr($user.put("primaryCityLatitude", $fullLike.primaryCityLatitude))
		$util.qr($user.put("nickname", $fullLike.nickname))
		$util.qr($user.put("state", $fullLike.state))
		$util.qr($user.put("email", $fullLike.email))
		$util.qr($user.put("primaryCityLongitude", $fullLike.primaryCityLongitude))
		$util.qr($user.put("isPremiumUser", $fullLike.isPremiumUser))
		$util.qr($user.put("userId", $fullLike.userId))
		$util.qr($user.put("primaryCityLongName", $fullLike.primaryCityLongName))
		$util.qr($user.put("dob", $fullLike.dob))
		
	    #set($like = {})
	    $util.qr($like.put("updatedAt", $fullLike.likeUpdatedAt))
	    $util.qr($like.put("likeReadByReceiver", $fullLike.likeReadByReceiver))
	    $util.qr($like.put("senderUser", $user))

	    $util.qr($likes.add($like))

    #end

#end

## build the json that the response needs
#set($result = {})
$util.qr($result.put("likes", $likes))
$util.qr($result.put("nextToken", $nextToken))
$util.toJson($result)
```

**Comment by cthomaschase** [comment]
Thanks @Ricardo1980 !
