### ISSUE TITLE
Allow VTL templates to define and use macros

### ISSUE THREAD

**Issue by davidmessem** [aws/aws-appsync-community#90]
I unsuccessfully tried to make use of the VTL standard macro functionality.
Below is an example of what I would like to do

```
#macro( escape $string )
  $string.replaceAll("'", "''").replaceAll...
#end

#set($safeName = "#escape($name)")
```

 I have read on the AWS forums that most standard tools and macros are blocked. Is there a particular reason for this? Can macros be allowed?

**Comment by hheavener-kyd** [comment]
I also have this issue. I would like to use a `math.random()` function into my mock response for API Gateway and am unable to do so.

**Comment by itrestian** [comment]
Thank you for the feedback! This is a feature request, we have heard this request in the past and I will +1 it internally on your behalf. As all feature requests, I cannot comment on the availability.

**Comment by Sunac** [comment]
Any news about this request? Or availability is still unknown?
This could significantly shorten some resolvers and that's an important thing as there is a mapping templates size limit.

**Comment by jkruse14** [comment]
Are there any updates to this request? This would be of great use to us as well!

**Comment by Sunac** [comment]
> 2 years since this request. Any updates please?

Still nothing but meanwhile I saw this nice trick from [MappingTool](https://twitter.com/mappingtool/status/1488544896361369601)

**Comment by onlybakam** [comment]
Hello, we currently do not support macros. We have released support for JavaScript resolvers which makes it easier to write your business logic. https://docs.aws.amazon.com/appsync/latest/devguide/resolver-reference-js-version.html
