### ISSUE TITLE
Caching return inconsistent data

### ISSUE THREAD

**Issue by 112Cracker** [aws/aws-appsync-community#92]
I am writing a video publish service using AppSync. I add a per-resolver caching for my app. And try to define caching on the below data schema.

Observation:
Inconsistent read on connection field (have unit resolvers) because of the cache

I have the below schema using Amplify Transform syntax
```
type Video @model{
id: ID!
userid: String! # owner of the video
userProfile: UserProfile @connection(fields:["userid"])
}

type UserProfile @model{
userid: String!
username: String
}
```

The userProfile field will have a unit resolver attached, and I tried to configure resolver caching for the userProfile under Video. After enable caching in the console, and set TTL to 60s.

I run the below queries in the Query console.
Use the 2 example data below
Example 1
user id: 3664378B-98F0-4CCC-A071-96E9EDDA6E51, username: bigpapiqa
video id: 125f95fa-e6ca-40ea-b58d-2c77ab6a1624 

Example 2
user id: 3C763F67-287D-479F-826C-0AD06FF30F91, username: lukas
video id: 077bbe37-9cd7-4a0c-ab68-e99da76a9cf0

In AppSync Query console
Step 1: Use the first video id
```
query getVideo {
  getVideo(id: "125f95fa-e6ca-40ea-b58d-2c77ab6a1624") {
    userid
    userProfile {
      userid
      username
    }
  }
}
```

Step 1 Result:
```
{
  "data": {
    "getSourceVideoPackage": {
      "userid": "3664378B-98F0-4CCC-A071-96E9EDDA6E51",
      "userProfile": {
        "userid": "3664378B-98F0-4CCC-A071-96E9EDDA6E51", # CONSISTENT
        "username": "bigpapiqa"
      }
    }
  }
}
```

Step 2: Use the second video id
```
query getVideo {
  getVideo(id: "077bbe37-9cd7-4a0c-ab68-e99da76a9cf0") {
    userid
    userProfile {
      userid
      username
    }
  }
}
```

Step 2 Result:
```
{
  "data": {
    "getSourceVideoPackage": {
      "userid": "3C763F67-287D-479F-826C-0AD06FF30F91",
      "userProfile": {
        "userid": "3664378B-98F0-4CCC-A071-96E9EDDA6E51", # IN-CONSISTENT!!! Seems to wrongly fetch from cache
        "username": "bigpapiqa"
      }
    }
  }
}
```
This is back to normal and consistent when wait after the caching TTL (60 s) and submit the same Step 2 query.

**Comment by 112Cracker** [comment]
I examined the request template for userProfile resolver. It is use the parent field userid to query the UserProfile table. But it seems to me, this subfield is fetching data directly from cache using the previous source.userid.
```
{
  "version": "2017-02-28",
  "operation": "GetItem",
  "key": {
      "owner": $util.dynamodb.toDynamoDBJson($util.defaultIfNullOrBlank($ctx.source.userid, "___xamznone____"))
  }
}
```

**Comment by ivid** [comment]
The problem here is that $context.source is not used (and not able to be used, per documentation) as a cache key, which is a problem for caching any resolver that's not top-level query/mutation.

https://docs.aws.amazon.com/appsync/latest/devguide/enabling-caching.html

**Comment by awsed** [comment]
We just implemented support for ctx.source so this should be sorted. Docs are also updated to reflect the change:
 
https://docs.aws.amazon.com/appsync/latest/devguide/enabling-caching.html
